select 	'PLR' as "BU"
		, coalesce(i.item_code, is2.item_set_id) as "FacilityMethodCode" 
		, coalesce((case when i.print_name != '' then i.print_name else i.common_name end), is2.description) as "FacilityMethodNameTH"
		, coalesce((case when i.print_name_en != '' then i.print_name_en else i.common_name end), is2.description) as "FacilityMethodNameEN"
		, '' as "EffectiveDateFrom"
		, is2.expire_date as "EffectiveDateto"
		, '0' as "GenderOnlyId"
		, 'None' as "GenderOnlyName"
		, '0 ปี 0 เดือน 0 วัน' as "NoDayAgeFrom"
		, '0 ปี 0 เดือน 0 วัน' as "NoDayAgeTo"
		, '0' as "UseOnlyIpdOpdTypeId"
		, 'None' as "UseOnlyIpdOpdTypeName"
		, '' as "CheckUpMethodCode"
		, '' as "CheckUpMethodNameTH"
		, '' as "CheckUpMethodNameEN"
		, '0 ปี 0 เดือน 0 วัน' as "NoDayRecallPeriod"
		, '0' as "GroupReqNormallyGenIPDDrugOrderId"
		, 'None' as "GroupReqNormallyGenIPDDrugOrderName"
		, '' as "ColourCode"
		, '' as "ColourNameTH"
		, '' as "ColourNameEN"
		, is2.is_fix_set_price as "CannotRebate"
		, coalesce(case when i.active = '1' then '0' else '1' end, '0') as "Off"
		, '0' as "HereUseAsAddition"
		, '0' as "FreeOfCharge"
		, '0' as "HereAddition"
		, '0' as "CheckUp"
		, case when is2.fix_order_set_type_id = '1' then '1' else '0' end as "Package"
		, '0' as "Common"
		, '' as "Memo"
from 	item_set is2 	
		left join item i on i.item_id = is2.item_id
where 	is2.fix_order_set_type_id in ('0','1')
order by is2.fix_order_set_type_id