select  'PLC' as "BU"
	  , a.patient_id as "PatientID"
	  , a.admit_id as "AdmitID"
	  , format_an(a.an) as "AN"
	  , to_char(a.admit_date ::timestamp,'dd/mm/yyyy')|| ' ' || substring(a.admit_time,0,6) as "MakeDateTime"
	  , to_char(a.begin_date ::timestamp,'dd/mm/yyyy')|| ' ' || substring(a.begin_time,0,6) as "InDateTime"
	  , to_char(a.end_date::timestamp,'dd/mm/yyyy')|| ' ' || substring(a.end_time,0,6) as "OutDateTime"
	  , '' as "AckDateTime"
	  , '' as "StartRmsFeeDateTime"
	  , to_char(a.modify_date::timestamp,'dd/mm/yyyy')|| ' ' || substring(a.modify_time,0,6) as "LastPostDateTime"
	  , bsp.base_service_point_id as "FromWardCode"
	  , bsp.description_th as "FromWardNameTH"
	  , bsp.description_en as "FromWardNameEN"
	  , bsp.base_service_point_id as "ToWardCode"
	  , bsp.description_th as "ToWardNameTH"
	  , bsp.description_en as "ToWardNameEN"
	  , bsp.base_service_point_id as "WardCode"
	  , bsp.description_th as "WardNameTH"
	  , bsp.description_en as "WardNameEN"
	  , bm.bed_number as "HNBedNo"
	  , '' as "HNBedNameTH"
	  , '' as "HNBedNameEN"
	  , bm.base_room_type_id as "HNRmsTypeCode"
	  , brt.description as "HNRmsTypeNameTH"
	  , '' as "HNRmsTypeNameEN"
	  , '' as "TransferInReasonCode"
	  , '' as "TransferInReasonNameTH"
	  , '' as "TransferInReasonNameEN"
	  , '' as "TransferOutReasonCode"
	  , '' as "TransferOutReasonNameTH"
	  , '' as "TransferOutReasonNameEN"
	  , '' as "Remarks"
	  , a.admit_eid as "InByUserCode"
	  , e.prename || ' ' || e.firstname || '  ' || e.lastname as "InByUserNameTH"
	  , e.intername as "InByUserNameEN"
	  , a.ipd_discharge as "OutByUserCode"
	  , e2.prename || ' ' || e2.firstname || '  ' || e2.lastname as "OutByUserNameTH"
	  , e2.intername as "OutByUserNameEN"
	  , case when a.is_observe != '1' then 0 else 1 end as "Observe"
from admit a 
inner join bed_management bm on a.admit_id = bm.admit_id 
left join base_service_point bsp on bm.base_service_point_id = bsp.base_service_point_id 
left join base_room_type brt on bm.base_room_type_id = brt.base_room_type_id 
left join employee e on a.admit_eid = e.employee_id 
left join employee e2 on a.ipd_discharge_eid = e2.employee_id 

