select 'PLR' as "BU"
, a.patient_id as "PatientID"
, a.admit_id as "AdmitID"
, a.admit_date as "AdmitDate"
, format_an(a.an) as "AN"
, '' as "Suffix"
, his_func_get_wardbed(a.admit_id,1) as "WardCode"
, his_func_get_wardbed(a.admit_id,2) as "WardNameTH"
, bsp.description_en as "WardNameEN"
, di.diagnosis_date ||' '|| di.diagnosis_time as "DiagDateTime"
, di.icd10_code as "PrimaryDiagnosisCode"
, di.icd10_description as "PrimaryDiagnosisNameTH"
, '' as "PrimaryDiagnosisNameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',1) as "ICDCmCode1"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',1) as "ICDCm1NameTH"
, '' as "ICDCm1NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',2) as "ICDCmCode2"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',2) as "ICDCm2NameTH"
, '' as "ICDCm2NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',3) as "ICDCmCode3"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',3) as "ICDCm3NameTH"
, '' as "ICDCm3NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',4) as "ICDCmCode4"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',4) as "ICDCm4NameTH"
, '' as "ICDCm4NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',5) as "ICDCmCode5"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',5) as "ICDCm5NameTH"
, '' as "ICDCm5NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',6) as "ICDCmCode6"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',6) as "ICDCm6NameTH"
, '' as "ICDCm6NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',7) as "ICDCmCode7"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',7) as "ICDCm7NameTH"
, '' as "ICDCm7NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',8) as "ICDCmCode8"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',8) as "ICDCm8NameTH"
, '' as "ICDCm8NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',9) as "ICDCmCode9"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',9) as "ICDCm9NameTH"
, '' as "ICDCm9NameEN"
, split_part(his_func_get_icd9(a.visit_id,'1'),'|',10) as "ICDCmCode10"
, split_part(his_func_get_icd9(a.visit_id,'2'),'|',10) as "ICDCm10NameTH"
, '' as "ICDCm10NameEN"
, di.modify_eid as "EntryByUserCode"
, e2.prename || e2.firstname || ' ' || e2.lastname as "EntryByUserNameTH"
, e2.intername as "EntryByUserNameEN"
, di.modify_date as "RegisterDate"
, '' as "ChronicCreteriaCode"
, '' as "ChronicCreteriaNameTH"
, '' as "ChronicCreteriaNameEN"
, e2.employee_id as "DoctorCode"
, e2.prename || e2.firstname || ' ' || e2.lastname as "DoctorNameTH"
, e2.intername as "DoctorNameEN"
, e2.profession_code as "DoctorCertificate"
, bd3.base_department_id as "DoctorClinicCode"
, bd3.description as "DoctorClinicNameTH"
, '' as "DoctorClinicNameEN"
, e2.base_med_department_id as "DoctorDepartmentCode"
, bmd.description as "DoctorDepartmentNameTH"
, '' as "DoctorDepartmentNameEN"
, e2.base_clinic_id as "DoctorSpecialtyCode"
, bmd.description as "DoctorSpecialtyNameTH"
, '' as "DoctorSpecialtyNameEN"
--***************************************** ECode ***************************************** 
, split_part(his_func_get_diagnosis(a.visit_id,'5','1'),'|',1) as "ECode"
, split_part(his_func_get_diagnosis(a.visit_id,'5','2'),'|',1) as "ECodeNameTH"
, '' as "ECodeNameEN"
, '' as "RemarksMemo"
--***************************************** UnderlyingICD ***************************************** 
, split_part(his_func_get_underlying(a.patient_id,1),'|',1) as "UnderlyingICDCode1"
, split_part(his_func_get_underlying(a.patient_id,2),'|',1) as "UnderlyingICD1NameTH"
, '' as "UnderlyingICD1NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',2) as "UnderlyingICDCode2"
, split_part(his_func_get_underlying(a.patient_id,2),'|',2) as "UnderlyingICD2NameTH"
, '' as "UnderlyingICD2NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',3) as "UnderlyingICDCode3"
, split_part(his_func_get_underlying(a.patient_id,2),'|',3) as "UnderlyingICD3NameTH"
, '' as "UnderlyingICD3NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',4) as "UnderlyingICDCode4"
, split_part(his_func_get_underlying(a.patient_id,2),'|',4) as "UnderlyingICD4NameTH"
, '' as "UnderlyingICD4NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',5) as "UnderlyingICDCode5"
, split_part(his_func_get_underlying(a.patient_id,2),'|',5) as "UnderlyingICD5NameTH"
, '' as "UnderlyingICD5NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',6) as "UnderlyingICDCode6"
, split_part(his_func_get_underlying(a.patient_id,2),'|',6) as "UnderlyingICD6NameTH"
, '' as "UnderlyingICD6NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',7) as "UnderlyingICDCode7"
, split_part(his_func_get_underlying(a.patient_id,2),'|',7) as "UnderlyingICD7NameTH"
, '' as "UnderlyingICD7NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',8) as "UnderlyingICDCode1"
, split_part(his_func_get_underlying(a.patient_id,2),'|',8) as "UnderlyingICD1NameTH"
, '' as "UnderlyingICD8NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',9) as "UnderlyingICDCode9"
, split_part(his_func_get_underlying(a.patient_id,2),'|',9) as "UnderlyingICD9NameTH"
, '' as "UnderlyingICD9NameEN"
, split_part(his_func_get_underlying(a.patient_id,1),'|',10) as "UnderlyingICDCode10"
, split_part(his_func_get_underlying(a.patient_id,2),'|',10) as "UnderlyingICD10NameTH"
, '' as "UnderlyingICD10NameEN"
--***************************************** ComplicationsICD ***************************************** 
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',1) as "ComplicationsICDCode1"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',1) as "ComplicationsICD1NameTH"
, '' as "ComplicationsICD1NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',2) as "ComplicationsICDCode2"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',2) as "ComplicationsICD2NameTH"
, '' as "ComplicationsICD2NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',3) as "ComplicationsICDCode3"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',3) as "ComplicationsICD3NameTH"
, '' as "ComplicationsICD3NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',4) as "ComplicationsICDCode4"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',4) as "ComplicationsICD4NameTH"
, '' as "ComplicationsICD4NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',5) as "ComplicationsICDCode5"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',5) as "ComplicationsICD5NameTH"
, '' as "ComplicationsICD5NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',6) as "ComplicationsICDCode6"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',6) as "ComplicationsICD6NameTH"
, '' as "ComplicationsICD6NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',7) as "ComplicationsICDCode7"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',1) as "ComplicationsICD7NameTH"
, '' as "ComplicationsICD7NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',8) as "ComplicationsICDCode8"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',8) as "ComplicationsICD8NameTH"
, '' as "ComplicationsICD8NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',9) as "ComplicationsICDCode9"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',9) as "ComplicationsICD9NameTH"
, '' as "ComplicationsICD9NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'3','1'),'|',10) as "ComplicationsICDCode10"
, split_part(his_func_get_diagnosis(a.visit_id,'3','2'),'|',10) as "ComplicationsICD10NameTH"
, '' as "ComplicationsICD10NameEN"
--***************************************** OtherICD ***************************************** 
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',1) as "OtherICDCode1"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',1) as "OtherICD1NameTH"
, '' as "OtherICD1NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',2) as "OtherICDCode2"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',2) as "OtherICD2NameTH"
, '' as "OtherICD2NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',3) as "OtherICDCode3"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',3) as "OtherICD3NameTH"
, '' as "OtherICD3NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',4) as "OtherICDCode4"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',4) as "OtherICD4NameTH"
, '' as "OtherICD4NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',5) as "OtherICDCode5"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',5) as "OtherICD5NameTH"
, '' as "OtherICD5NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',6) as "OtherICDCode6"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',6) as "OtherICD6NameTH"
, '' as "OtherICD6NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',7) as "OtherICDCode7"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',7) as "OtherICD7NameTH"
, '' as "OtherICD7NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',8) as "OtherICDCode8"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',8) as "OtherICD8NameTH"
, '' as "OtherICD8NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',9) as "OtherICDCode9"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',9) as "OtherICD9NameTH"
, '' as "OtherICD9NameEN"
, split_part(his_func_get_diagnosis(a.visit_id,'4','1'),'|',10) as "OtherICDCode10"
, split_part(his_func_get_diagnosis(a.visit_id,'4','2'),'|',10) as "OtherICD10NameTH"
, '' as "OtherICD10NameEN"
--***************************************** OperationDoctor *****************************************
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',1) as "OperationDoctorCode1"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',1) as "OperationDoctor1NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',1) as "OperationDoctor1NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',2) as "OperationDoctorCode2"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',2) as "OperationDoctor2NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',2) as "OperationDoctor2NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',3) as "OperationDoctorCode3"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',3) as "OperationDoctor3NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',3) as "OperationDoctor3NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',4) as "OperationDoctorCode4"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',4) as "OperationDoctor4NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',4) as "OperationDoctor4NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',5) as "OperationDoctorCode5"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',5) as "OperationDoctor5NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',5) as "OperationDoctor5NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',6) as "OperationDoctorCode6"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',6) as "OperationDoctor6NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',6) as "OperationDoctor6NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',7) as "OperationDoctorCode7"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',7) as "OperationDoctor7NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',7) as "OperationDoctor7NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',8) as "OperationDoctorCode8"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',8) as "OperationDoctor8NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',8) as "OperationDoctor8NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',9) as "OperationDoctorCode9"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',9) as "OperationDoctor9NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',9) as "OperationDoctor9NameEN"
, split_part(his_func_get_icd9(a.visit_id,'3'),'|',10) as "OperationDoctorCode10"
, split_part(his_func_get_icd9(a.visit_id,'4'),'|',10) as "OperationDoctor10NameTH"
, split_part(his_func_get_icd9(a.visit_id,'5'),'|',10) as "OperationDoctor10NameEN"
from admit a 
left join base_department bd on bd.base_department_id = a.base_department_id 
left join diagnosis_icd10 di on di.visit_id = a.visit_id and di.fix_diagnosis_type_id = '1'
left join employee e2 on e2.employee_id = di.doctor_eid 
left join patient p on p.patient_id = a.patient_id
left join base_clinic bc on bc.base_clinic_id = e2.base_clinic_id
left join base_department bmd on bmd.base_department_id = e2.base_med_department_id
left join base_service_point bsp2 on e2.base_service_point_id = bsp2.base_service_point_id 
left join base_department bd3 on bsp2.base_department_id = bd3.base_department_id 
left join bed_management bm on bm.admit_id = a.admit_id
left join base_service_point bsp on bsp.base_service_point_id = bm.base_service_point_id
limit 10

