select top 100
		  'PTP' as 'BU'
		, pti.HN as 'PatientID'
		, pti.FACILITYRMSNO as 'FacilityRmsNo'
		, pti.REQUESTNO as 'RequestNo'
		, adm.AN as 'AN'
		, adb.BEDNO as 'HNBedNo'
		, dbo.sysconname(adb.BEDNO,20084,2) as 'HNBedNameTH'
		, dbo.sysconname(adb.BEDNO,20084,1) as 'HNBedNameEN'
		, adm.ADMWARD as 'Ward'
		, dbo.sysconname(adm.ADMWARD,20024,2) as 'WardNameTH'
		, dbo.sysconname(adm.ADMWARD,20024,1) as 'WardNameEN'
		, adm.ADMTYPE as 'AdmCode'
		, dbo.sysconname(adm.ADMTYPE,20048,2) as 'AdmNameTH'
		, dbo.sysconname(adm.ADMTYPE,20048,1) as 'AdmNameEN'
		, docadm.DOCTOR as 'AdmDoctor'
		, dbo.Doctorname(docadm.DOCTOR,2) as 'AdmDoctorNameTH'
		, dbo.Doctorname(docadm.DOCTOR,1) as 'AdmDoctorNameEN'
		, adm.PATIENTTYPE as 'PatientType'
		, dbo.sysconname(adm.PATIENTTYPE,20011,2) as 'PatientTypeNameTH'
		, dbo.sysconname(adm.PATIENTTYPE,20011,1) as 'PatientTypeNameEN'
		, adm.USEDRIGHTCODE as 'RightCode'
		, dbo.sysconname(adm.USEDRIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(adm.USEDRIGHTCODE,20019,1) as 'RightNameEN'
		, pt.NATIONALITY as 'NationalityCode'
		, dbo.sysconname(pt.NATIONALITY,10072,2) as 'NationalityNameTH'
		, dbo.sysconname(pt.NATIONALITY,10072,1) as 'NationalityNameEN'
		, pt.RACE as 'RaceCode'
		, dbo.sysconname(pt.RACE,10080,2) as 'RaceNameTH'
		, dbo.sysconname(pt.RACE,10080,1) as 'RaceNameEN'
		, pti.INFANT_BORNORDER as 'BornOrder'
		, pt.SEX as 'Gender'
		, IIF(pt.SEX = 1 , 'ªÒÂ' , 'Ë­Ô§') as 'GenderNameTH'
		, IIF(pt.SEX = 1 , 'Male' , 'Female')  as 'GenderNameEN'
		, dbo.CutSortChar(ptnt.FIRSTNAME) as 'FirstThaiName'
		, dbo.CutSortChar(ptnt.LASTNAME) as 'LastThaiName'
		, dbo.CutSortChar(ptne.FIRSTNAME) as 'FirstEnglishName'
		, dbo.CutSortChar(ptne.LASTNAME) as 'LastEnglishName'
		, pt.BIRTHDATETIME as 'BirthDateTime'
		, pt.DEADDATETIME as 'DeadDateTime'
		, lrd.ALIVECODE as 'LRAliveCode'
		, dbo.sysconname(lrd.ALIVECODE,20207,2) as 'LRAliveNameTH'
		, dbo.sysconname(lrd.ALIVECODE,20207,1) as 'LRAliveNameEN'
		, pti.INFANT_LRMODE as 'LRMode'
		, dbo.sysconname(pti.INFANT_LRMODE,20017,2) as 'LRModeNameTH'
		, dbo.sysconname(pti.INFANT_LRMODE,20017,1) as 'LRModeNameEN'
		, pti.INDICATION as 'IndicationCode1'
		, dbo.sysconname(pti.INDICATION,20165,2) as 'IndicationNameTH1'
		, dbo.sysconname(pti.INDICATION,20165,1) as 'IndicationNameEN1'
		, pti.INDICATION2 as 'IndicationCode2'
		, dbo.sysconname(pti.INDICATION2,20165,2) as 'IndicationNameTH2'
		, dbo.sysconname(pti.INDICATION2,20165,1) as 'IndicationNameEN2'
		, pti.INDICATION3 as 'IndicationCode3'
		, dbo.sysconname(pti.INDICATION3,20165,2) as 'IndicationNameTH3'
		, dbo.sysconname(pti.INDICATION3,20165,1) as 'IndicationNameEN3'
		, lrd.NOGADAY as 'NoGADay'
		, pti.INFANT_WEIGHTGM as 'WeightGm'
		, pti.INFANT_LENGTHCM as 'LengthCm'
		, pti.INFANT_TEMPERATURE as 'Temperature'
		, pti.INFANT_TEMPERATURE2 as 'Temperature2'
		, '' as 'HNLRExpireType'
		, pti.MENTOOCCIPITAL as 'MentoOccipital'
		, pti.INFANT_CHESTCM as 'ChestCm'
		, pti.APGARSCOREONEMINUTE as 'ApgarScoreOneMinute'
		, pti.APGARSCORETHREEMINUTE as 'ApgarScoreThreeMinute'
		, pti.APGARSCOREFIVEMINUTE as 'ApgarScoreFiveMinute'
		, pti.APGARSCORETENMINUTE as 'ApgarScoreTenMinute'
		, lrd.NEWBORNRESULTCODE as 'LRNewBornResultCode'
		, dbo.sysconname(lrd.NEWBORNRESULTCODE,20543,2) as 'LRNewBornResultNameTH'
		, dbo.sysconname(lrd.NEWBORNRESULTCODE,20543,1) as 'LRNewBornResultNameEN'
		, '' as 'LRNewBornResultCode2'
		, '' as 'LRNewBornResultNameTH2'
		, '' as 'LRNewBornResultNameEN2'
		, '' as 'LRNewBornResultCode3'
		, '' as 'LRNewBornResultNameTH3'
		, '' as 'LRNewBornResultNameEN3'
		, lrd.LRMEDICATIONCODE as 'LRMedicationCode1'
		, dbo.sysconname(lrd.LRMEDICATIONCODE,20542,2) as 'LRMedicationNameTH1'
		, dbo.sysconname(lrd.LRMEDICATIONCODE,20542,1) as 'LRMedicationNameEN1'
		, '' as 'LRMedicationCode2'
		, '' as 'LRMedicationNameTH2'
		, '' as 'LRMedicationNameEN2'
		, lrd.INDICATIONOFOPERATION1 as 'IndicationOfOperation1'
		, '' as 'IndicationOfOperationNameTH1'
		, '' as 'IndicationOfOperationNameEN1'
		, lrd.IndicationOfOperation2 as 'IndicationOfOperation2'
		, '' as 'IndicationOfOperationNameTH2'
		, '' as 'IndicationOfOperationNameEN2'
		, pti.AbnormalOnChild1 as 'AbnormalOnChildCode1'
		, '' as 'AbnormalOnChildNameTH1'
		, '' as 'AbnormalOnChildNameEN1'
		, pti.AbnormalOnChild2 as 'AbnormalOnChildCode2'
		, '' as 'AbnormalOnChildNameTH2'
		, '' as 'AbnormalOnChildNameEN2'
					from PATIENT_INFANT pti
					left join LRCHILD lrd on pti.HN=lrd.HN and pti.FACILITYRMSNO=lrd.FACILITYRMSNO and pti.REQUESTNO=lrd.REQUESTNO
					LEFT join PATIENT_INFO pt on pti.HN=pt.HN
					LEFT join PATIENT_NAME ptnt on pti.HN=ptnt.HN and ptnt.SUFFIX = 0
					LEFT join PATIENT_NAME ptne on pti.HN=ptne.HN and ptne.SUFFIX = 1
					left join (select ROW_NUMBER() OVER(PARTITION BY HN ORDER BY admdatetime ASC) AS Row#,* from ADMMASTER)
					adm on pti.HN=adm.HN and adm.Row# = 1
					left join ADMBED adb on adm.AN=adb.AN
					left join IPDDOCTOR doc on adm.AN=doc.AN and doc.SPECIALIZEDOCTORTYPE = 1
					left join IPDDOCTOR docadm on adm.AN=docadm.AN and docadm.THISDOCTORADM = 1