select 
		'PTP' as 'BU'
		,lrh.HN as 'PatientID'
		,lrh.FACILITYRMSNO as 'FacilityRmsNo'
		,lrh.REQUESTNO as 'RequestNo'
		,lrh.ENTRYDATETIME as 'EntryDateTime'
		,lrh.LRBEDNO as 'LRBedNo'
		,dbo.CutSortChar(bed.THAINAME) as 'LRBedNameTH'
		,dbo.CutSortChar(bed.ENGLISHNAME) as 'LRBedNameEN'
		,lrh.WARD as 'Ward'
		,dbo.sysconname(lrh.WARD,20024,2) as 'WardNameTH'
		,dbo.sysconname(lrh.WARD,20024,1) as 'WardNameEN'
		,lrh.PATIENTTYPE as 'PatientType'
		,dbo.sysconname(lrh.PATIENTTYPE,20011,2) as 'PatientTypeNameTH'
		,dbo.sysconname(lrh.PATIENTTYPE,20011,1) as 'PatientTypeNameEN'
		,lrh.TOTALBORN as 'TotalBorn'
		,'' as 'NoLivingChild'
		,'' as 'Gravidarum'
		,lrh.RIGHTCODE as 'RightCode'
		,dbo.sysconname(lrh.RIGHTCODE,20019,2) as 'RightNameTH'
		,dbo.sysconname(lrh.RIGHTCODE,20019,1) as 'RightNameEN'
		,lrh.LMPDATE as 'LMP'
		,lrh.EDCDATETIME as 'EDC'
		,lrh.NOGADAYBYUS as 'NoGADay'
		,'' as 'DateTimePlan'
		,lrh.INDATETIME as 'IN_DateTime'
		,'' as 'OUT_DateTime'
		,lrh.REQUESTDOCTOR as 'RequestDoctor'
		,dbo.CutSortChar(doc.THAINAME) as 'RequestDoctorNameTH'
		,dbo.CutSortChar(doc.ENGLISHNAME) as 'RequestDoctorNameEN'
		,lrh.ANCTYPECODE as 'ANCTypeCode'
		,dbo.sysconname(lrh.ANCTYPECODE,20316,2) as 'ANCTypeNameTH'
		,dbo.sysconname(lrh.ANCTYPECODE,20316,1) as 'ANCTypeNameEN'
		,lrh.INDICATIONOFOPERATION1 as 'IndicationOfOperation1'
		,dbo.sysconname(lrh.INDICATIONOFOPERATION1,20165,2) as 'IndicationOfOperationNameTH1'
		,dbo.sysconname(lrh.INDICATIONOFOPERATION1,20165,1) as 'IndicationOfOperationNameEN1'
		,lrh.INDICATIONOFOPERATION2 as 'IndicationOfOperation2'
		,dbo.sysconname(lrh.INDICATIONOFOPERATION2,20165,2) as 'IndicationOfOperationNameTH2'
		,dbo.sysconname(lrh.INDICATIONOFOPERATION2,20165,1) as 'IndicationOfOperationNameEN2'
		,lrh.INDICATIONOFOPERATION3 as 'IndicationOfOperation3'
		,dbo.sysconname(lrh.INDICATIONOFOPERATION3,20165,2) as 'IndicationOfOperationNameTH3'
		,dbo.sysconname(lrh.INDICATIONOFOPERATION3,20165,1) as 'IndicationOfOperationNameEN3'
		,lrh.INDUCTIONOFDELIVERY as 'LRInductionCode'
		,dbo.sysconname(lrh.INDUCTIONOFDELIVERY,20168,2) as 'LRInductionNameTH'
		,dbo.sysconname(lrh.INDUCTIONOFDELIVERY,20168,1) as 'LRInductionNameEN'
		,lrh.INHIBITCODE as 'LRInhibitCode'
		,dbo.sysconname(lrh.INHIBITCODE,20453,2) as 'LRInhibitNameTH'
		,dbo.sysconname(lrh.INHIBITCODE,20453,1) as 'LRInhibitNameEN'
		,'' as 'InLabourRmsStatusCode'
		,'' as 'InLabourRmsStatusNameTH'
		,'' as 'InLabourRmsStatusNameEN'
		,lrh.LASTABORTDATE as 'LastAbort'
		,lrh.LASTCHILDDATE as 'LastChild'
		,'' as 'RefFromCode'
		,'' as 'RefFromNameTH'
		,'' as 'RefFromNameEN'
		,'' as 'RefFromHospital'
		,'' as 'RefFromHospitalNameTH'
		,'' as 'RefFromHospitalNameEN'
		,dbo.CutSortChar(lrh.HUSBANDFIRSTNAME) as 'HusbandFirstName'
		,dbo.CutSortChar(lrh.HUSBANDLASTNAME) as 'HusbandLastName'
		,lrh.CLINIC as 'Clinic'
		,dbo.sysconname(lrh.CLINIC,20016,2) as 'ClinicNameTH'
		,dbo.sysconname(lrh.CLINIC,20016,1) as 'ClinicNameEN'
		,lrh.REQUESTBYUSERCODE as 'RequestByUserCode'
		,dbo.sysconname(lrh.REQUESTBYUSERCODE,10000,2) as 'RequestByUserNameTH'
		,dbo.sysconname(lrh.REQUESTBYUSERCODE,10000,1) as 'RequestByUserNameEN'
		,'' as 'LRPackageCode'
		,'' as 'LRPackageNameTH'
		,'' as 'LRPackageNameEN'
		,case when lrh.ALREADYSETTLE = 0 then 'None'
			  when lrh.ALREADYSETTLE = 1 then 'Charged'
			  when lrh.ALREADYSETTLE = 2 then 'Paid Out'
			  when lrh.ALREADYSETTLE = 3 then 'Working'
			  when lrh.ALREADYSETTLE = 4 then 'Free Of Charge'
		 end as HNAlready
		,'' as 'CxlDateTime'
		,lrh.CXLREASONCODE as 'CxlReasonCode'
		,dbo.sysconname(lrh.CXLREASONCODE,20587,2) as 'CxlReasonNameTH'
		,dbo.sysconname(lrh.CXLREASONCODE,20587,1) as 'CxlReasonNameEN'
			from LRREQ lrh
			left join HNBEDINV bed on lrh.LRBEDNO=bed.BEDNO
			left join HNDOCTOR doc on lrh.REQUESTDOCTOR=doc.DOCTOR