select top 100 
'PT2' as 'BU'
,a.HN as 'PatientID'
,CONVERT(varchar,a.ADMDATETIME,112)+a.AN as 'AdmitID'
,a.ADMDATETIME as 'AdmitDateTime'
,ipdv.AN as 'AN'
,ipdv.Ward as 'LocationCode'
,dbo.sysconname(ipdv.Ward,42201,2) as 'LocationNameTH'
,dbo.sysconname(ipdv.Ward,42201,1) as 'LocationNameEN'
,ipdv.EntryByUserCode as 'EntryByUserCode' 
,dbo.sysconname(ipdv.EntryByUserCode,10031,2) as 'EntryByUserNameTH'
,dbo.sysconname(ipdv.EntryByUserCode,10031,1) as 'EntryByUserNameEN'
,ipdv.EntryDateTime as 'EntryDateTime'
,ipdv.BodyWeight as 'BodyWeight'
,ipdv.Height as 'Height'
,CONVERT(decimal(10,2), (case when ipdv.BodyWeight = 0 then null else ipdv.BodyWeight end)/((case when ipdv.Height = 0 then null else ipdv.Height/100 end)*(case when ipdv.Height = 0 then null else ipdv.Height/100 end))) as 'BMI'
,ipdv.PostBpSystolic as 'PostBpSystolic'
,ipdv.PostBpDiastolic as 'PostBpDiastolic'
,ipdv.BpSystolic as 'BpSystolic'
,ipdv.BpDiastolic as 'BpDiastolic'
,ipdv.Temperature as 'Temperature'
,ipdv.PulseRate as 'PulseRate'
,ipdv.RespirationRate as 'RespirationRate'
,ipdv.PainScale as 'PainScale' 
,ipdv.O2Sat as 'O2Sat'
,ipdv.Remarks as 'Remark'
		from HNIPD_VITALSIGN ipdv
		left join HNIPD_MASTER a on ipdv.AN=a.AN