select top 10 
'PLS' as BU,
adm.HN as PatientID,
CONVERT(varchar,adm.ADMDATETIME,112)+adm.AN as AdmitID,
adm.ADMDATETIME as AdmitDate,
adm.AN as AN,
ipddiag.SUFFIX as Suffix,
adm.ADMWARD as WardCode,
dbo.sysconname(ADM.ADMWARD,20024,2) as WardNameTH,
dbo.sysconname(ADM.ADMWARD,20024,1) as WardNameEN,
ipddiag.DIAGNOSESDATE as DiagDateTime,
ipddiag.DIAGNOSES as PrimaryDiagnosisCode,
icd.THAINAME as PrimaryDiagnosisNameTH,
icd.ENGLISHNAME as PrimaryDiagnosisNameEN,


ipddiag.PROCUDUREICDCMCODE as ICDCmCode1,
icdcm.THAINAME as ICDCm1NameTH,
icdcm.ENGLISHNAME as ICDCm1NameEN,
ipddiag.PROCUDUREICDCMCODE2 as ICDCmCode2,
icdcm2.THAINAME as ICDCm2NameTH,
icdcm2.ENGLISHNAME as ICDCm2NameEN,
ipddiag.PROCUDUREICDCMCODE3 as ICDCmCode3,
icdcm3.THAINAME as ICDCm3NameTH,
icdcm3.ENGLISHNAME as ICDCm3NameEN,
ipddiag.PROCUDUREICDCMCODE4 as ICDCmCode4,
icdcm4.THAINAME as ICDCm4NameTH,
icdcm4.ENGLISHNAME as ICDCm4NameEN,
(select a.PROCUDUREICDCMCODE from IPDSUMMARY a where a.AN=adm.AN and a.SUFFIX = 2) as ICDCmCode5,
(select b.THAINAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm5NameTH,
(select b.ENGLISHNAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm5NameEN,
(select a.PROCUDUREICDCMCODE2 from IPDSUMMARY a where a.AN=adm.AN and a.SUFFIX = 2) as ICDCmCode6,
(select b.THAINAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE2 = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm6NameTH,
(select b.ENGLISHNAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE2 = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm6NameEN,
(select a.PROCUDUREICDCMCODE3 from IPDSUMMARY a where a.AN=adm.AN and a.SUFFIX = 2) as ICDCmCode7,
(select b.THAINAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE3 = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm7NameTH,
(select b.ENGLISHNAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE3 = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm7NameEN,
(select a.PROCUDUREICDCMCODE4 from IPDSUMMARY a where a.AN=adm.AN and a.SUFFIX = 2) as ICDCmCode8,
(select b.THAINAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE4 = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm8NameTH,
(select b.ENGLISHNAME from IPDSUMMARY a left join ICDCM_MASTER b on a.PROCUDUREICDCMCODE4 = b.ICDCMCODE and a.SUFFIX = 2 where a.AN=adm.AN and a.SUFFIX = 2) as ICDCm8NameEN,
'' as ICDCmCode9,
'' as ICDCm9NameTH,
'' as ICDCm9NameEN,
'' as ICDCmCode10,
'' as ICDCm10NameTH,
'' as ICDCm10NameEN,


ipddiag.ENTRYBYUSERCODE as EntryByUserCode,
dbo.sysconname(ipddiag.ENTRYBYUSERCODE,10000,2) as EntryByUserNameTH,
dbo.sysconname(ipddiag.ENTRYBYUSERCODE,10000,1) as EntryByUserNameEN,
'' as RegisterDate,
'' as ChronicCreteriaCode,
'' as ChronicCreteriaNameTH,
'' as ChronicCreteriaNameEN,
ipddiag.DOCTOR as DoctorCode,
dbo.Doctorname(ipddiag.DOCTOR,2) as DoctorNameTH,
dbo.Doctorname(ipddiag.DOCTOR,1) as DoctorNameEN,
doc.CERTIFYPUBLICNO as DoctorCertificate,
doc.CLINIC as DoctorClinicCode,
dbo.sysconname(doc.clinic,20016,2) as DoctorClinicNameTH,
dbo.sysconname(doc.clinic,20016,1) as DoctorClinicNameEN,
'' as DoctorDepartmentCode,
'' as DoctorDepartmentNameTH,
'' as DoctorDepartmentNameEN,
doc.SPECIALTY+doc.SUBSPECIALTY as DoctorSpecialtyCode,
dbo.CutSortChar(ssp.thainame) as DoctorSpecialtyNameTH,
dbo.CutSortChar(ssp.ENGLISHNAME) as DoctorSpecialtyNameEN,
ipddiag.ECODE as Ecode,
dbo.ICDname(ipddiag.ECODE,2) as ECodeNameTH,
dbo.ICDname(ipddiag.ECODE,1) as ECodeNameEN,
ipddiag.REMARKS as RemarksMemo,


ipddiag.UNDERLYINGCAUSE as UnderlyingICDCode1,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE,2) as UnderlyingICD1NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE,1) as UnderlyingICD1NameEN,
ipddiag.UNDERLYINGCAUSE2 as UnderlyingICDCode2,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE2,2) as UnderlyingICD2NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE2,1) as UnderlyingICD2NameEN,
ipddiag.UNDERLYINGCAUSE3 as UnderlyingICDCode3,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE3,2) as UnderlyingICD3NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE3,1) as UnderlyingICD3NameEN,
ipddiag.UNDERLYINGCAUSE4 as UnderlyingICDCode4,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE4,2) as UnderlyingICD4NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE4,1) as UnderlyingICD4NameEN,
ipddiag.UNDERLYINGCAUSE5 as UnderlyingICDCode5,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE5,2) as UnderlyingICD5NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE5,1) as UnderlyingICD5NameEN,
(select a.UNDERLYINGCAUSE from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICDCode6,
(select dbo.ICDname(a.UNDERLYINGCAUSE,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD6NameTH,
(select dbo.ICDname(a.UNDERLYINGCAUSE,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD6NameEN,
(select a.UNDERLYINGCAUSE2 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICDCode7,
(select dbo.ICDname(a.UNDERLYINGCAUSE2,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD7NameTH,
(select dbo.ICDname(a.UNDERLYINGCAUSE2,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD7NameEN,
(select a.UNDERLYINGCAUSE3 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICDCode8,
(select dbo.ICDname(a.UNDERLYINGCAUSE3,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD8NameTH,
(select dbo.ICDname(a.UNDERLYINGCAUSE3,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD8NameEN,
(select a.UNDERLYINGCAUSE4 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICDCode9,
(select dbo.ICDname(a.UNDERLYINGCAUSE4,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD9NameTH,
(select dbo.ICDname(a.UNDERLYINGCAUSE4,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD9NameEN,
(select a.UNDERLYINGCAUSE5 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICDCode10,
(select dbo.ICDname(a.UNDERLYINGCAUSE5,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD10NameTH,
(select dbo.ICDname(a.UNDERLYINGCAUSE5,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as UnderlyingICD10NameEN,


ipddiag.COMPLICATIONS as ComplicationsICDCode1,
dbo.ICDname(ipddiag.COMPLICATIONS,2) as ComplicationsICD1NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS,1) as ComplicationsICD1NameEN,
ipddiag.COMPLICATIONS2 as ComplicationsICDCode2,
dbo.ICDname(ipddiag.COMPLICATIONS2,2) as ComplicationsICD2NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS2,1) as ComplicationsICD2NameEN,
ipddiag.COMPLICATIONS3 as ComplicationsICDCode3,
dbo.ICDname(ipddiag.COMPLICATIONS3,2) as ComplicationsICD3NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS3,1) as ComplicationsICD3NameEN,
ipddiag.COMPLICATIONS4 as ComplicationsICDCode4,
dbo.ICDname(ipddiag.COMPLICATIONS4,2) as ComplicationsICD4NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS4,1) as ComplicationsICD4NameEN,
ipddiag.COMPLICATIONS5 as ComplicationsICDCode5,
dbo.ICDname(ipddiag.COMPLICATIONS5,2) as ComplicationsICD5NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS5,1) as ComplicationsICD5NameEN,
(select a.COMPLICATIONS from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICDCode6,
(select dbo.ICDname(a.COMPLICATIONS,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD6NameTH,
(select dbo.ICDname(a.COMPLICATIONS,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD6NameEN,
(select a.COMPLICATIONS2 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICDCode7,
(select dbo.ICDname(a.COMPLICATIONS2,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD7NameTH,
(select dbo.ICDname(a.COMPLICATIONS2,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD7NameEN,
(select a.COMPLICATIONS3 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICDCode8,
(select dbo.ICDname(a.COMPLICATIONS3,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD8NameTH,
(select dbo.ICDname(a.COMPLICATIONS3,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD8NameEN,
(select a.COMPLICATIONS4 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICDCode9,
(select dbo.ICDname(a.COMPLICATIONS4,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD9NameTH,
(select dbo.ICDname(a.COMPLICATIONS4,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD9NameEN,
(select a.COMPLICATIONS5 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICDCode10,
(select dbo.ICDname(a.COMPLICATIONS5,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD10NameTH,
(select dbo.ICDname(a.COMPLICATIONS5,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as ComplicationsICD10NameEN,


ipddiag.OTHERDIAGNOSES as OtherICDCode1,
dbo.ICDname(ipddiag.OTHERDIAGNOSES,2) as OtherICD1NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES,1) as OtherICD1NameEN,
ipddiag.OTHERDIAGNOSES2 as OtherICDCode2,
dbo.ICDname(ipddiag.OTHERDIAGNOSES2,2) as OtherICD2NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES2,1) as OtherICD2NameEN,
ipddiag.OTHERDIAGNOSES3 as OtherICDCode3,
dbo.ICDname(ipddiag.OTHERDIAGNOSES3,2) as OtherICD3NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES3,1) as OtherICD3NameEN,
ipddiag.OTHERDIAGNOSES4 as OtherICDCode4,
dbo.ICDname(ipddiag.OTHERDIAGNOSES4,2) as OtherICD4NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES4,1) as OtherICD4NameEN,
ipddiag.OTHERDIAGNOSES5 as OtherICDCode5,
dbo.ICDname(ipddiag.OTHERDIAGNOSES5,2) as OtherICD5NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES5,1) as OtherICD5NameEN,
(select a.OTHERDIAGNOSES from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX = 2) as OtherICDCode6,
(select dbo.ICDname(a.OTHERDIAGNOSES,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD6NameTH,
(select dbo.ICDname(a.OTHERDIAGNOSES,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD6NameEN,
(select a.OTHERDIAGNOSES2 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX = 2) as OtherICDCode7,
(select dbo.ICDname(a.OTHERDIAGNOSES2,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD7NameTH,
(select dbo.ICDname(a.OTHERDIAGNOSES2,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD7NameEN,
(select a.OTHERDIAGNOSES3 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX = 2) as OtherICDCode8,
(select dbo.ICDname(a.OTHERDIAGNOSES3,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD8NameTH,
(select dbo.ICDname(a.OTHERDIAGNOSES3,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD8NameEN,
(select a.OTHERDIAGNOSES4 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX = 2) as OtherICDCode9,
(select dbo.ICDname(a.OTHERDIAGNOSES4,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD9NameTH,
(select dbo.ICDname(a.OTHERDIAGNOSES4,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD9NameEN,
(select a.OTHERDIAGNOSES5 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX = 2) as OtherICDCode10,
(select dbo.ICDname(a.OTHERDIAGNOSES5,2) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD10NameTH,
(select dbo.ICDname(a.OTHERDIAGNOSES5,1) from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX=2) as OtherICD10NameEN,


ipddiag.DOCTOR2 as OperationDoctorCode1,
dbo.Doctorname(ipddiag.DOCTOR2,2) as OperationDoctor1NameTH,
dbo.Doctorname(ipddiag.DOCTOR2,1) as OperationDoctor1NameEN,
ipddiag.DOCTOR3 as OperationDoctorCode2,
dbo.Doctorname(ipddiag.DOCTOR3,2) as OperationDoctor2NameTH,
dbo.Doctorname(ipddiag.DOCTOR3,1) as OperationDoctor2NameEN,
ipddiag.DOCTOR4 as OperationDoctorCode3,
dbo.Doctorname(ipddiag.DOCTOR4,2) as OperationDoctor3NameTH,
dbo.Doctorname(ipddiag.DOCTOR4,1) as OperationDoctor3NameEN,
ipddiag.DOCTOR5 as OperationDoctorCode4,
dbo.Doctorname(ipddiag.DOCTOR5,2) as OperationDoctor4NameTH,
dbo.Doctorname(ipddiag.DOCTOR5,1) as OperationDoctor4NameEN,
(select a.DOCTOR2 from IPDSUMMARY a where ipddiag.AN=a.AN and a.SUFFIX = 2) as OperationDoctorCode5,
(select dbo.Doctorname(a.DOCTOR2,2) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor5NameTH,
(select dbo.Doctorname(a.DOCTOR2,1) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor5NameEN,
(select a.DOCTOR3 from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctorCode6,
(select dbo.Doctorname(a.DOCTOR3,2) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor6NameTH,
(select dbo.Doctorname(a.DOCTOR3,1) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor6NameEN,
(select a.DOCTOR4 from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctorCode7,
(select dbo.Doctorname(a.DOCTOR4,2) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor7NameTH,
(select dbo.Doctorname(a.DOCTOR4,1) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor7NameEN,
(select a.DOCTOR5 from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctorCode8,
(select dbo.Doctorname(a.DOCTOR5,2) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor8NameTH,
(select dbo.Doctorname(a.DOCTOR5,1) from IPDSUMMARY a where a.AN=ipddiag.AN and a.SUFFIX = 2) as OperationDoctor8NameEN,
'' as OperationDoctorCode9,
'' as OperationDoctor9NameTH,
'' as OperationDoctor9NameEN,
'' as OperationDoctorCode10,
'' as OperationDoctor10NameTH,
'' as OperationDoctor10NameEN


		from ADMMASTER adm
		inner join IPDSUMMARY ipddiag on ipddiag.AN=adm.AN and ipddiag.SUFFIX = 1
		left join HNDOCTOR doc on ipddiag.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
		left join ICD_MASTER icd on ipddiag.DIAGNOSES=icd.ICDCODE
		left join ICDCM_MASTER icdcm on ipddiag.PROCUDUREICDCMCODE=icdcm.ICDCMCODE
		left join ICDCM_MASTER icdcm2 on ipddiag.PROCUDUREICDCMCODE2=icdcm2.ICDCMCODE
		left join ICDCM_MASTER icdcm3 on ipddiag.PROCUDUREICDCMCODE3=icdcm3.ICDCMCODE
		left join ICDCM_MASTER icdcm4 on ipddiag.PROCUDUREICDCMCODE4=icdcm4.ICDCMCODE

	