select top 10 
'PLS' as BU,
adm.HN as PatientID,
CONVERT(varchar,adm.ADMDATETIME,112)+adm.AN as AdmitID,
adm.ADMDATETIME as AdmitDate,
adm.AN as AN,
ipddiag.SUFFIX as Suffix,
adm.ADMWARD as WardCode,
dbo.sysconname(ADM.ADMWARD,20024,2) as WardNameTH,
dbo.sysconname(ADM.ADMWARD,20024,1) as WardNameEN,
ipddiag.DIAGNOSESDATE as DiagDateTime,
ipddiag.DIAGNOSES as PrimaryDiagnosisCode,
icd.THAINAME as PrimaryDiagnosisNameTH,
icd.ENGLISHNAME as PrimaryDiagnosisNameEN,


ipddiag.PROCUDUREICDCMCODE as ICDCmCode1,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE,2) as ICDCm1NameTH,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE,1) as ICDCm1NameEN,
ipddiag.PROCUDUREICDCMCODE2 as ICDCmCode2,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE2,2) as ICDCm2NameTH,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE2,1) as ICDCm2NameEN,
ipddiag.PROCUDUREICDCMCODE3 as ICDCmCode3,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE3,2) as ICDCm3NameTH,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE3,1) as ICDCm3NameEN,
ipddiag.PROCUDUREICDCMCODE4 as ICDCmCode4,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE4,2) as ICDCm4NameTH,
dbo.ICDCMname(ipddiag.PROCUDUREICDCMCODE4,1) as ICDCm4NameEN,
ipddiag2.PROCUDUREICDCMCODE as ICDCmCode5,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE,2) as ICDCm5NameTH,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE,1) as ICDCm5NameEN,
ipddiag2.PROCUDUREICDCMCODE2 as ICDCmCode6,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE2,2) as ICDCm6NameTH,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE2,1) as ICDCm6NameEN,
ipddiag2.PROCUDUREICDCMCODE3 as ICDCmCode7,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE3,2) as ICDCm7NameTH,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE3,1) as ICDCm7NameEN,
ipddiag2.PROCUDUREICDCMCODE4 as ICDCmCode8,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE4,2) as ICDCm8NameTH,
dbo.ICDCMname(ipddiag2.PROCUDUREICDCMCODE4,1) as ICDCm8NameEN,
'' as ICDCmCode9,
'' as ICDCm9NameTH,
'' as ICDCm9NameEN,
'' as ICDCmCode10,
'' as ICDCm10NameTH,
'' as ICDCm10NameEN,


ipddiag.ENTRYBYUSERCODE as EntryByUserCode,
dbo.sysconname(ipddiag.ENTRYBYUSERCODE,10000,2) as EntryByUserNameTH,
dbo.sysconname(ipddiag.ENTRYBYUSERCODE,10000,1) as EntryByUserNameEN,
'' as RegisterDate,
'' as ChronicCreteriaCode,
'' as ChronicCreteriaNameTH,
'' as ChronicCreteriaNameEN,
ipddiag.DOCTOR as DoctorCode,
dbo.Doctorname(ipddiag.DOCTOR,2) as DoctorNameTH,
dbo.Doctorname(ipddiag.DOCTOR,1) as DoctorNameEN,
doc.CERTIFYPUBLICNO as DoctorCertificate,
doc.CLINIC as DoctorClinicCode,
dbo.sysconname(doc.clinic,20016,2) as DoctorClinicNameTH,
dbo.sysconname(doc.clinic,20016,1) as DoctorClinicNameEN,
'' as DoctorDepartmentCode,
'' as DoctorDepartmentNameTH,
'' as DoctorDepartmentNameEN,
doc.SPECIALTY+doc.SUBSPECIALTY as DoctorSpecialtyCode,
dbo.CutSortChar(ssp.thainame) as DoctorSpecialtyNameTH,
dbo.CutSortChar(ssp.ENGLISHNAME) as DoctorSpecialtyNameEN,
ipddiag.ECODE as Ecode,
dbo.ICDname(ipddiag.ECODE,2) as ECodeNameTH,
dbo.ICDname(ipddiag.ECODE,1) as ECodeNameEN,
ipddiag.REMARKS as RemarksMemo,


ipddiag.UNDERLYINGCAUSE as UnderlyingICDCode1,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE,2) as UnderlyingICD1NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE,1) as UnderlyingICD1NameEN,
ipddiag.UNDERLYINGCAUSE2 as UnderlyingICDCode2,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE2,2) as UnderlyingICD2NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE2,1) as UnderlyingICD2NameEN,
ipddiag.UNDERLYINGCAUSE3 as UnderlyingICDCode3,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE3,2) as UnderlyingICD3NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE3,1) as UnderlyingICD3NameEN,
ipddiag.UNDERLYINGCAUSE4 as UnderlyingICDCode4,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE4,2) as UnderlyingICD4NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE4,1) as UnderlyingICD4NameEN,
ipddiag.UNDERLYINGCAUSE5 as UnderlyingICDCode5,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE5,2) as UnderlyingICD5NameTH,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE5,1) as UnderlyingICD5NameEN,
ipddiag2.UNDERLYINGCAUSE as UnderlyingICDCode6,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE,2) as UnderlyingICD6NameTH,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE,1) as UnderlyingICD6NameEN,
ipddiag2.UNDERLYINGCAUSE2 as UnderlyingICDCode7,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE2,2) as UnderlyingICD7NameTH,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE2,1) as UnderlyingICD7NameEN,
ipddiag2.UNDERLYINGCAUSE3 as UnderlyingICDCode8,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE3,2) as UnderlyingICD8NameTH,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE3,1) as UnderlyingICD8NameEN,
ipddiag2.UNDERLYINGCAUSE4 as UnderlyingICDCode9,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE4,2) as UnderlyingICD9NameTH,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE4,1) as UnderlyingICD9NameEN,
ipddiag2.UNDERLYINGCAUSE5 as UnderlyingICDCode10,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE5,2) as UnderlyingICD10NameTH,
dbo.ICDname(ipddiag2.UNDERLYINGCAUSE5,1) as UnderlyingICD10NameEN,



ipddiag.COMPLICATIONS as ComplicationsICDCode1,
dbo.ICDname(ipddiag.COMPLICATIONS,2) as ComplicationsICD1NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS,1) as ComplicationsICD1NameEN,
ipddiag.COMPLICATIONS2 as ComplicationsICDCode2,
dbo.ICDname(ipddiag.COMPLICATIONS2,2) as ComplicationsICD2NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS2,1) as ComplicationsICD2NameEN,
ipddiag.COMPLICATIONS3 as ComplicationsICDCode3,
dbo.ICDname(ipddiag.COMPLICATIONS3,2) as ComplicationsICD3NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS3,1) as ComplicationsICD3NameEN,
ipddiag.COMPLICATIONS4 as ComplicationsICDCode4,
dbo.ICDname(ipddiag.COMPLICATIONS4,2) as ComplicationsICD4NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS4,1) as ComplicationsICD4NameEN,
ipddiag.COMPLICATIONS5 as ComplicationsICDCode5,
dbo.ICDname(ipddiag.COMPLICATIONS5,2) as ComplicationsICD5NameTH,
dbo.ICDname(ipddiag.COMPLICATIONS5,1) as ComplicationsICD5NameEN,
ipddiag2.COMPLICATIONS as ComplicationsICDCode6,
dbo.ICDname(ipddiag2.COMPLICATIONS,2) as ComplicationsICD6NameTH,
dbo.ICDname(ipddiag2.COMPLICATIONS,1) as ComplicationsICD6NameEN,
ipddiag2.COMPLICATIONS2 as ComplicationsICDCode7,
dbo.ICDname(ipddiag2.COMPLICATIONS2,2) as ComplicationsICD7NameTH,
dbo.ICDname(ipddiag2.COMPLICATIONS2,1) as ComplicationsICD7NameEN,
ipddiag2.COMPLICATIONS3 as ComplicationsICDCode8,
dbo.ICDname(ipddiag2.COMPLICATIONS3,2) as ComplicationsICD8NameTH,
dbo.ICDname(ipddiag2.COMPLICATIONS3,1) as ComplicationsICD8NameEN,
ipddiag2.COMPLICATIONS4 as ComplicationsICDCode9,
dbo.ICDname(ipddiag2.COMPLICATIONS4,2) as ComplicationsICD9NameTH,
dbo.ICDname(ipddiag2.COMPLICATIONS4,1) as ComplicationsICD9NameEN,
ipddiag2.COMPLICATIONS5 as ComplicationsICDCode10,
dbo.ICDname(ipddiag2.COMPLICATIONS5,2) as ComplicationsICD10NameTH,
dbo.ICDname(ipddiag2.COMPLICATIONS5,1) as ComplicationsICD10NameEN,



ipddiag.OTHERDIAGNOSES as OtherICDCode1,
dbo.ICDname(ipddiag.OTHERDIAGNOSES,2) as OtherICD1NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES,1) as OtherICD1NameEN,
ipddiag.OTHERDIAGNOSES2 as OtherICDCode2,
dbo.ICDname(ipddiag.OTHERDIAGNOSES2,2) as OtherICD2NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES2,1) as OtherICD2NameEN,
ipddiag.OTHERDIAGNOSES3 as OtherICDCode3,
dbo.ICDname(ipddiag.OTHERDIAGNOSES3,2) as OtherICD3NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES3,1) as OtherICD3NameEN,
ipddiag.OTHERDIAGNOSES4 as OtherICDCode4,
dbo.ICDname(ipddiag.OTHERDIAGNOSES4,2) as OtherICD4NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES4,1) as OtherICD4NameEN,
ipddiag.OTHERDIAGNOSES5 as OtherICDCode5,
dbo.ICDname(ipddiag.OTHERDIAGNOSES5,2) as OtherICD5NameTH,
dbo.ICDname(ipddiag.OTHERDIAGNOSES5,1) as OtherICD5NameEN,
ipddiag2.OTHERDIAGNOSES as OtherICDCode6,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES,2) as OtherICD6NameTH,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES,1) as OtherICD6NameEN,
ipddiag2.OTHERDIAGNOSES2 as OtherICDCode7,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES2,2) as OtherICD7NameTH,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES2,1) as OtherICD7NameEN,
ipddiag2.OTHERDIAGNOSES3 as OtherICDCode8,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES3,2) as OtherICD8NameTH,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES3,1) as OtherICD8NameEN,
ipddiag2.OTHERDIAGNOSES4 as OtherICDCode9,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES4,2) as OtherICD9NameTH,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES4,1) as OtherICD9NameEN,
ipddiag2.OTHERDIAGNOSES5 as OtherICDCode10,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES5,2) as OtherICD10NameTH,
dbo.ICDname(ipddiag2.OTHERDIAGNOSES5,1) as OtherICD10NameEN,


ipddiag.DOCTOR2 as OperationDoctorCode1,
dbo.Doctorname(ipddiag.DOCTOR2,2) as OperationDoctor1NameTH,
dbo.Doctorname(ipddiag.DOCTOR2,1) as OperationDoctor1NameEN,
ipddiag.DOCTOR3 as OperationDoctorCode2,
dbo.Doctorname(ipddiag.DOCTOR3,2) as OperationDoctor2NameTH,
dbo.Doctorname(ipddiag.DOCTOR3,1) as OperationDoctor2NameEN,
ipddiag.DOCTOR4 as OperationDoctorCode3,
dbo.Doctorname(ipddiag.DOCTOR4,2) as OperationDoctor3NameTH,
dbo.Doctorname(ipddiag.DOCTOR4,1) as OperationDoctor3NameEN,
ipddiag.DOCTOR5 as OperationDoctorCode4,
dbo.Doctorname(ipddiag.DOCTOR5,2) as OperationDoctor4NameTH,
dbo.Doctorname(ipddiag.DOCTOR5,1) as OperationDoctor4NameEN,
ipddiag2.DOCTOR2 as OperationDoctorCode5,
dbo.Doctorname(ipddiag2.DOCTOR2,2) as OperationDoctor5NameTH,
dbo.Doctorname(ipddiag2.DOCTOR2,1) as OperationDoctor5NameEN,
ipddiag2.DOCTOR3 as OperationDoctorCode6,
dbo.Doctorname(ipddiag2.DOCTOR3,2) as OperationDoctor6NameTH,
dbo.Doctorname(ipddiag2.DOCTOR3,1) as OperationDoctor6NameEN,
ipddiag2.DOCTOR4 as OperationDoctorCode7,
dbo.Doctorname(ipddiag2.DOCTOR4,2) as OperationDoctor7NameTH,
dbo.Doctorname(ipddiag2.DOCTOR4,1) as OperationDoctor7NameEN,
ipddiag2.DOCTOR5 as OperationDoctorCode8,
dbo.Doctorname(ipddiag2.DOCTOR5,2) as OperationDoctor8NameTH,
dbo.Doctorname(ipddiag2.DOCTOR5,1) as OperationDoctor8NameEN,
'' as OperationDoctorCode9,
'' as OperationDoctor9NameTH,
'' as OperationDoctor9NameEN,
'' as OperationDoctorCode10,
'' as OperationDoctor10NameTH,
'' as OperationDoctor10NameEN


		from ADMMASTER adm
		inner join IPDSUMMARY ipddiag on ipddiag.AN=adm.AN and ipddiag.SUFFIX = 1
		left join IPDSUMMARY ipddiag2 on ipddiag2.AN=adm.AN and ipddiag2.SUFFIX = 2
		left join HNDOCTOR doc on ipddiag.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
		left join ICD_MASTER icd on ipddiag.DIAGNOSES=icd.ICDCODE

	