Select
		  'PTP' as 'BU'
		, convert(varchar(25), adm.AdmDateTime, 112) + replace(replace(adm.AN,'/',''),'-','') + FORMAT(dh.MAKEDATETIME, 'yyyyMMddHHmmss') +  CONVERT(Varchar,ROW_NUMBER()OVER(PARTITION BY dh.ORDERNO ORDER BY dh.makedatetime ASC))  as 'OrderID'
		, adm.HN as 'PatientID'
		, convert(varchar(25), adm.ADMDATETIME, 112) + replace(replace(adm.AN,'/',''),'-','') as 'AdmitID'
		, adm.ADMDATETIME as 'AdmitDateTime'
		, adm.AN as 'AN'
		, adm.MAKEDATETIME as 'MakeDateTime'
		, dh.ORDERNO as 'DrugOrderNo'
		, dh.STORE as 'StoreCode'
		, dbo.sysconname(dh.STORE,40010,2) as 'StoreNameTH'
		, dbo.sysconname(dh.STORE,40010,1) as 'StoreNameEN'
		, dh.STOCKCODE as 'ItemCode'
		, dbo.CutSortChar(stm.THAINAME) as 'ItemNameTH'
		, dbo.CutSortChar(stm.ENGLISHNAME) as 'ItemNameEN'
		, Case When dh.[REVERSE] = 1 Then dh.QTY*(-1) Else dh.QTY End as 'Qty'
		, dh.UNITCODE as 'UnitCode'
		, dbo.sysconname(dh.UNITCODE,40016,2) as 'UnitNameTH'
		, dbo.sysconname(dh.UNITCODE,40016,1) as 'UnitNameEN'
		, dh.UNITPRICE as 'UnitPrice'
		, dh.AMT as 'ChargeAmt'
		, dh.CHARGECODE as 'HNActivityCode'
		, dbo.sysconname(dh.CHARGECODE,20023,2) as 'HNActivityNameTH'
		, dbo.sysconname(dh.CHARGECODE,20023,1) as 'HNActivityNameEN'
		, dh.RIGHTCODE as 'RightCode'
		, dbo.sysconname(dh.RIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(dh.RIGHTCODE,20019,1) as 'RightNameEN'
		, '' as 'DispendDrugReasonCode'
		, '' as 'DispendDrugReasonNameTH'
		, '' as 'DispendDrugReasonNameEN'
		, dh.DOSETYPE as 'DoseTypeCode'
		, dbo.sysconname(dh.DOSETYPE,20031,2) as 'DoseTypeNameTH'
		, dbo.sysconname(dh.DOSETYPE,20031,1) as 'DoseTypeNameEN'
		, dh.DOSECODE as 'DoseCode'
		, dbo.sysconname(dh.DOSECODE,20032,2) as 'DoseNameTH'
		, dbo.sysconname(dh.DOSECODE,20032,1) as 'DoseNameEN'
		, CAST(SUBSTRING(sys01.COM,1,1)as Int) as 'NumberDosePerDay'
		, '' as 'BeforeAfterMealType'
		, '' as 'BeforeAfterMealTypeName'
		, dh.DOSEQTYCODE as 'DoseQtyCode'
		, dbo.sysconname(dh.DOSEQTYCODE,20033,2) as 'DoseQtyNameTH'
		, dbo.sysconname(dh.DOSEQTYCODE,20033,1) as 'DoseQtyNameEN'
		, '' as 'IPDDrugOrderQtyTypeCode'
		, '' as 'IPDDrugOrderQtyTypeName'
		, dh.DOSEUNITCODE as 'DoseUnitCode'
		, dbo.sysconname(dh.DOSEUNITCODE,20034,2) as 'DoseUnitNameTH'
		, dbo.sysconname(dh.DOSEUNITCODE,20034,1) as 'DoseUnitNameEN'
		, dh.NODAYDOSE as 'NumberDayDose'
		, '' as 'DoseFreqCode'
		, '' as 'DoseFreqNameTH'
		, '' as 'DoseFreqNameEN'
		, dh.AUXLABEL1 as 'AuxLabel1Code'
		, dbo.sysconname(dh.AUXLABEL1,20030,2) as 'AuxLabel1NameTH'
		, dbo.sysconname(dh.AUXLABEL1,20030,1) as 'AuxLabel1NameEN'
		, dh.AUXLABEL2 as 'AuxLabel2Code'
		, dbo.sysconname(dh.AUXLABEL2,20030,2) as 'AuxLabel2NameTH'
		, dbo.sysconname(dh.AUXLABEL2,20030,1) as 'AuxLabel2NameEN'
		, dh.AUXLABEL3 as 'AuxLabel3Code'
		, dbo.sysconname(dh.AUXLABEL3,20030,2) as 'AuxLabel3NameTH'
		, dbo.sysconname(dh.AUXLABEL3,20030,1) as 'AuxLabel3NameEN'
		, dh.DOSEMEMO as 'DoseMemo'
		, dt.RETURNDRUGREASON as 'ReturnIpdDrugReasonCode'
		, dbo.sysconname(dt.RETURNDRUGREASON,20639,2) as 'ReturnIpdDrugReasonnameTH'
		, dbo.sysconname(dt.RETURNDRUGREASON,20639,1) as 'ReturnIpdDrugReasonNameEN'
		, stm.NETPRICE as 'NetPrice'
		, '' as 'OutsideHospitalDrug'
		, dt.MEDICINEORDERTYPE as 'MedicineOrderTypeCode'
		, Case When dt.MEDICINEORDERTYPE = 0 Then 'Continue'
			   When dt.MEDICINEORDERTYPE = 1 Then 'OneDay'
			   When dt.MEDICINEORDERTYPE = 2 Then 'Stat'
			   When dt.MEDICINEORDERTYPE = 3 Then 'TakeHome'
		  End as 'MedicineOrderTypeName'
		, '' as 'HNDrugErrorCodeTypeCode'
		, '' as 'HNDrugErrorCodeTypeName'
		, '' as 'HNAllergicErrorCodeTypeCode'
		, '' as 'HNAllergicErrorCodeTypeName'
		, '' as 'StartDoseDateTime'
		, '' as 'StopDateTime'
		, '' as 'MarDateTime1'
		, '' as 'MarDateTime2'
		, '' as 'MarDateTime3'
		, '' as 'MarDateTime4'
		, '' as 'MarDateTime5'
		, '' as 'MarDateTime6'
				From IPDDRUGHIST dh
				Inner Join ADMMASTER adm on dh.AN=adm.AN
				inner Join SSBSTOCK.dbo.STOCK_MASTER stm on dh.STOCKCODE=stm.STOCKCODE and stm.MAINCATEGORY = 'ME'
				Left Join SYSCONFIG sys01 on dh.DOSECODE=sys01.CODE and sys01.CTRLCODE=20032
				inner Join IPDORDDTL dt on dh.ORDERNO=dt.ORDERNO and dh.STOCKCODE=dt.STOCKCODE
				Where CONVERT(Date,dh.MAKEDATETIME)=CONVERT(Date,Getdate())
				--and dh.ORDERNO = 'D6904-00531'
