select top 10 
'PLS' as BU,
adm.HN as PatientID,
CONVERT(varchar,adm.ADMDATETIME,112)+adm.AN as AdmitID,
adm.ADMDATETIME as AdmitDate,
adm.AN as AN,
ipddiag.SUFFIX as Suffix,
adm.ADMWARD as LocationCode,
dbo.sysconname(ADM.ADMWARD,20024,2) as LocationNameTH, --แก้ไขวันที่ 03/03/2568
dbo.sysconname(ADM.ADMWARD,20024,1) as LocationNameEN, --เพิ่มวันที่ 03/03/2568
ipddiag.DIAGENDDATETIME as DiagDateTime, 
ipddiag.DIAGNOSES as ICDCode,
SUBSTRING(icd.ENGLISHNAME,2,500) as ICDName,
ipddiag.PROCUDUREICDCMCODE as ICDCmCode1,
SUBSTRING(icdcm.ENGLISHNAME,2,500) as ICDCmName1,
ipddiag.PROCUDUREICDCMCODE2 as ICDCmCode2,
SUBSTRING(icdcm2.ENGLISHNAME,2,500) as ICDCmName2,
ipddiag.PROCUDUREICDCMCODE3 as ICDCmCode3,
SUBSTRING(icdcm3.ENGLISHNAME,2,500) as ICDCmName3,
ipddiag.PROCUDUREICDCMCODE4 as ICDCmCode4,
SUBSTRING(icdcm4.ENGLISHNAME,2,500) as ICDCmName4,
'' as ICDCmCode5,
'' as ICDCmName5,
'' as ICDCmCode6,
'' as ICDCmName6,
'' as ICDCmCode7,
'' as ICDCmName7,
'' as ICDCmCode8,
'' as ICDCmName8,
'' as ICDCmCode9,
'' as ICDCmName9,
'' as ICDCmCode10,
'' as ICDCmName10,
ipddiag.ENTRYBYUSERCODE as EntryByUserCode, --แก้ไขวันที่ 03/03/2568
dbo.sysconname(ipddiag.ENTRYBYUSERCODE,10000,2) as EntryByUserNameTH, --เพิ่มวันที่ 03/03/2568
dbo.sysconname(ipddiag.ENTRYBYUSERCODE,10000,1) as EntryByUserNameEN, --เพิ่มวันที่ 03/03/2568
'' as RegisterDate,
'' as ChronicCreteriaCode,
'' as ChronicCreteriaName,
ipddiag.MASTERDOCTOR as DoctorCode,
dbo.Doctorname(ipddiag.MASTERDOCTOR,2) as DoctorNameTH,
dbo.Doctorname(ipddiag.MASTERDOCTOR,1) as DoctorNameEN,
ipddiag.ECODE as Ecode,
dbo.ICDname(ipddiag.ECODE,3) as ECodeName,
ipddiag.REMARKS as RemarksMemo,
ipddiag.UNDERLYINGCAUSE as UnderlyingICDCode1,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE,3) as UnderlyingICDName1,
ipddiag.UNDERLYINGCAUSE2 as UnderlyingICDCode2,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE2,3) as UnderlyingICDName2,
ipddiag.UNDERLYINGCAUSE3 as UnderlyingICDCode3,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE3,3) as UnderlyingICDName3,
ipddiag.UNDERLYINGCAUSE4 as UnderlyingICDCode4,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE4,3) as UnderlyingICDName4,
ipddiag.UNDERLYINGCAUSE5 as UnderlyingICDCode5,
dbo.ICDname(ipddiag.UNDERLYINGCAUSE5,3) as UnderlyingICDName5,
ipddiag.COMPLICATIONS as ComplicationsICDCode1,
dbo.ICDname(ipddiag.COMPLICATIONS,3) as ComplicationsICDName1,
ipddiag.COMPLICATIONS2 as ComplicationsICDCode2,
dbo.ICDname(ipddiag.COMPLICATIONS2,3) as ComplicationsICDName2,
ipddiag.COMPLICATIONS3 as ComplicationsICDCode3,
dbo.ICDname(ipddiag.COMPLICATIONS3,3) as ComplicationsICDName3,
ipddiag.COMPLICATIONS4 as ComplicationsICDCode4,
dbo.ICDname(ipddiag.COMPLICATIONS4,3) as ComplicationsICDName4,
ipddiag.COMPLICATIONS5 as ComplicationsICDCode5,
dbo.ICDname(ipddiag.COMPLICATIONS5,3) as ComplicationsICDName5,
ipddiag.OTHERDIAGNOSES as OtherICDCode1,
dbo.ICDname(ipddiag.OTHERDIAGNOSES,3) as OtherICDName1,
ipddiag.OTHERDIAGNOSES2 as OtherICDCode2,
dbo.ICDname(ipddiag.OTHERDIAGNOSES2,3) as OtherICDName2,
ipddiag.OTHERDIAGNOSES3 as OtherICDCode3,
dbo.ICDname(ipddiag.OTHERDIAGNOSES3,3) as OtherICDName3,
ipddiag.OTHERDIAGNOSES4 as OtherICDCode4,
dbo.ICDname(ipddiag.OTHERDIAGNOSES4,3) as OtherICDName4,
ipddiag.DOCTOR as OperationDoctorCode1,
dbo.Doctorname(ipddiag.DOCTOR,2) as OperationDoctorName1,
ipddiag.DOCTOR2 as OperationDoctorCode2,
dbo.Doctorname(ipddiag.DOCTOR2,2) as OperationDoctorName2,
ipddiag.DOCTOR3 as OperationDoctorCode3,
dbo.Doctorname(ipddiag.DOCTOR3,2) as OperationDoctorName3,
ipddiag.DOCTOR4 as OperationDoctorCode4,
dbo.Doctorname(ipddiag.DOCTOR4,2) as OperationDoctorName4,
ipddiag.DOCTOR5 as OperationDoctorCode5,
dbo.Doctorname(ipddiag.DOCTOR5,2) as OperationDoctorName5,
'' as OperationDoctorCode6,
'' as OperationDoctorName6,
'' as OperationDoctorCode7,
'' as OperationDoctorName7,
'' as OperationDoctorCode8,
'' as OperationDoctorName8,
'' as OperationDoctorCode9,
'' as OperationDoctorName9,
'' as OperationDoctorCode10,
'' as OperationDoctorName10
		from ADMMASTER adm
		left join IPDSUMMARY ipddiag on ipddiag.AN=adm.AN
		left join ICD_MASTER icd on ipddiag.DIAGNOSES=icd.ICDCODE
		left join ICDCM_MASTER icdcm on ipddiag.PROCUDUREICDCMCODE=icdcm.ICDCMCODE
		left join ICDCM_MASTER icdcm2 on ipddiag.PROCUDUREICDCMCODE2=icdcm2.ICDCMCODE
		left join ICDCM_MASTER icdcm3 on ipddiag.PROCUDUREICDCMCODE3=icdcm3.ICDCMCODE
		left join ICDCM_MASTER icdcm4 on ipddiag.PROCUDUREICDCMCODE4=icdcm4.ICDCMCODE

	