select  top 10
'PLS' as 'BU'
,a.HN as 'PatientID'
,CONVERT(varchar,a.ADMDATETIME,112)+a.AN as 'AdmitID'
,a.ADMDATETIME as 'AdmitDateTime'
,ipdv.AN as 'AN'
,a.ADMWARD as 'LocationCode'
,dbo.sysconname(a.ADMWARD,20024,2) as 'LocationNameTH'
,dbo.sysconname(a.ADMWARD,20024,1) as 'LocationNameEN'
,ipdv.ENTRYBYUSERCODE as 'EntryByUserCode'
,dbo.sysconname(ipdv.ENTRYBYUSERCODE,10000,2) as 'EntryByUserNameTH'
,dbo.sysconname(ipdv.ENTRYBYUSERCODE,10000,1) as 'EntryByUserNameEN'
,ipdv.ENTRYDATETIME as 'EntryDateTime'
,ipdv.BODYWEIGHT as 'BodyWeight'
,ipdv.HEIGHT as 'Height'
,CONVERT(decimal(10,2),(case when ipdv.BODYWEIGHT = 0 then null else ipdv.BODYWEIGHT end)/((case when ipdv.HEIGHT = 0 then null else ipdv.HEIGHT/100 end)*(case when ipdv.HEIGHT = 0 then null else ipdv.HEIGHT/100 end))) 'BMI'
,ipdv.POSTBPHIGH as 'PostBpSystolic'
,ipdv.POSTBPLOW as 'PostBpDiastolic'
,ipdv.BPHIGH as 'BpSystolic'
,ipdv.BPLOW as 'BpDiastolic'
,ipdv.TEMPERATURE as 'Temperature'
,ipdv.TEXTPULSERATE as 'PulseRate'
,ipdv.TEXTRESPIRERATE as 'RespirationRate'
,'' as 'PainScale'
,'' as 'O2Sat'
,ipdv.REMARKS as 'Remark'
		from IPDVITAL ipdv
		left join ADMMASTER a on ipdv.AN=a.AN