select top 10
		 'PT2' as 'BU'
		, xh.HN as 'PatientID'
		, xh.FacilityRmsNo as 'FacilityRmsNo'
		, xh.RequestNo as 'RequestNo'
		, xh.EntryDateTime as 'EntryDateTime'
		, xh.RequestDoctor as 'RequestDoctorCode'
		, dbo.Doctorname(xh.RequestDoctor,2) as 'RequestDoctorNameTH'
		, dbo.Doctorname(xh.RequestDoctor,1) as 'RequestDoctorNameEN'
		, xh.ACKDATETIME as 'AcknowledgeDateTime'
		, '' as 'ResultSuffixSmall'
		, xs.XRAYCODE as 'XrayCode'
		, dbo.sysconname(xs.XRAYCODE,20073,2) as 'XrayNameTH'
		, dbo.sysconname(xs.XRAYCODE,20073,1) as 'XrayNameEN'
		, xs.RESULTDATETIME as 'ConfirmResultDateTime'
		, xs.ResultDoctor as 'ResultDoctorCode'
		, dbo.Doctorname(xs.ResultDoctor,2) as 'ResultDoctorNameTH'
		, dbo.Doctorname(xs.ResultDoctor,1) as 'ResultDoctorNameEN'
		, xs.ResultMemo as 'ResultMemo'
		, xs.CxlByUserCode as 'CancelByUserCode'
		, dbo.sysconname(xs.CxlByUserCode,10000,2) as 'CancelByUserNameTH'
		, dbo.sysconname(xs.CxlByUserCode,10000,1) as 'CancelByUserNameEN'
		, xs.CxlDateTime as 'CancelDateTime'
				from XRAYREQ xh
				left join XRAYRESULT xs on xh.FacilityRmsNo=xs.FacilityRmsNo and xh.RequestNo=xs.RequestNo