select top 10 
'PLS' as 'BU'
,HN as 'PatientID'
,HN as 'HN'
,case when SUFFIX = 0 then 'None'
	  when SUFFIX = 1 then 'All'
	  when SUFFIX = 2 then 'Reception'
	  when SUFFIX = 3 then 'Cashier'
	  when SUFFIX = 4 then 'Diag Room'
	  when SUFFIX = 5 then 'Social Hx'
	  when SUFFIX = 6 then 'Family Hx'
	  when SUFFIX = 7 then 'Vacination'
	  when SUFFIX = 8 then 'Allergic'
	  when SUFFIX = 9 then 'Major Problem'
	  when SUFFIX = 10 then 'Past History'
	  when SUFFIX = 11 then 'Pharmacy'
	  when SUFFIX = 12 then 'Xray'
	  when SUFFIX = 13 then 'Lab'
	  when SUFFIX = 14 then 'Cashier to Cashier'
	  when SUFFIX = 15 then 'OR to Anes.'
	  when SUFFIX = 16 then 'Personal Info(1)'
	  when SUFFIX = 17 then 'Personal Info(2)'
	  when SUFFIX = 18 then 'Personal Info(3)'
	  when SUFFIX = 19 then 'Nutrition(1)'
	  when SUFFIX = 20 then 'Nutrition(2)'
	  end as 'MessageType'
,MEMO as 'Message'
,LASTUPDATEDATETIME as 'EntryDateTime'
,USERCODE as 'EntryByUserCode' --แก้ไขวันที่ 24/02/2568
,dbo.sysconname(USERCODE,10000,2) as 'EntryByUserNameTH' --เพิ่มวันที่ 24/02/2568
,dbo.sysconname(USERCODE,10000,1) as 'EntryByUserNameEN' --เพิ่มวันที่ 24/02/2568
,'Active' as 'Status'
,'' as 'EffectiveDateTimeFrom'
,'' as 'EffectiveDateTimeTo'
		from PATIENT_MSG
