select 	da."BU",
		da."PatientID",
		da."HN",
		row_number() over(partition by da."PatientID" order by da."Makedatetime") as "Suffix",
    	da."Pharmacoindex",
    	da."Pharmacoindexname",
    	da."StockingredientCode",
    	da."StockingredientName",
	    da."MedicinestructureCode",
    	da."MedicinestructureName",
	    da."WithgenericName",
	    da."StockCode",
	    da."StockName",
	    da."Adversereactions1",
	    da."Adversereactions1Name",
	    da."Adversereactions2",
	    da."Adversereactions2Name",
	    da."Adversereactions3",
	    da."Adversereactions3Name",
	    da."AdverseReactions4",
	    da."Adversereactions4Name",
	    da."Adversereactions5",
	    da."Adversereactions5Name",
	    da."Adversereactions6",
	    da."Adversereactions6Name",
	    da."Remark",
	    da."Makedatetime",
	    da."Status",
	    da."InactiveDate",
	    da."InactiveByUserCode" ,
	    da."InactiveByUserNameTH" ,
	    da."InactiveByUserNameEN" 
from 
(
SELECT 	'PLC' as "BU",
		da.patient_id as "PatientID",
		format_hn(p.hn) AS "HN",
    	replace(split_part(da.adr_group_name::text, '['::text, 2), ']'::text, ''::text) AS "Pharmacoindex",
    	split_part(da.adr_group_name::text, '['::text, 1) AS "Pharmacoindexname",
    	''::text AS "StockingredientCode",
    	''::text AS "StockingredientName",
	    ''::text AS "MedicinestructureCode",
    	''::text AS "MedicinestructureName",
	    da.generic_name AS "WithgenericName",
	    ''::text AS "StockCode",
	    ''::text AS "StockName",
	    ''::text AS "Adversereactions1",
	    split_part(da.symptom, ','::text, 1) AS "Adversereactions1Name",
	    ''::text AS "Adversereactions2",
	    split_part(da.symptom, ','::text, 2) AS "Adversereactions2Name",
	    ''::text AS "Adversereactions3",
	    split_part(da.symptom, ','::text, 3) AS "Adversereactions3Name",
	    ''::text AS "AdverseReactions4",
	    split_part(da.symptom, ','::text, 4) AS "Adversereactions4Name",
	    ''::text AS "Adversereactions5",
	    split_part(da.symptom, ','::text, 5) AS "Adversereactions5Name",
	    ''::text AS "Adversereactions6",
	    split_part(da.symptom, ','::text, 6) AS "Adversereactions6Name",
	    da.note as "Remark",
	    case when da.record_date != '' then  ((da.record_date::text || ' '::text) || da.record_time::text)::timestamp without time zone else null end AS "Makedatetime",
	    'Active' as "Status",
	    ''::text AS "InactiveDate",
	    '' as "InactiveByUserCode" ,
	    '' as "InactiveByUserNameTH" ,
	    '' as "InactiveByUserNameEN" 
FROM 	drug_allergy da
	    LEFT JOIN patient p ON da.patient_id::text = p.patient_id::text
--where 	da.patient_id  in (select v.patient_id from visit v where v.visit_date = '2024-01-01')
union all 
SELECT 	'PLC' as "BU",
		tda.patient_id as "PatientID",
		format_hn(p.hn) AS "HN",
    	replace(split_part(tda.adr_group_name::text, '['::text, 2), ']'::text, ''::text) AS "Pharmacoindex",
    	split_part(tda.adr_group_name::text, '['::text, 1) AS "Pharmacoindexname",
    	''::text AS "StockingredientCode",
    	''::text AS "StockingredientName",
	    ''::text AS "MedicinestructureCode",
    	''::text AS "MedicinestructureName",
	    tda.generic_name AS "WithgenericName",
	    ''::text AS "StockCode",
	    ''::text AS "StockName",
	    ''::text AS "Adversereactions1",
	    split_part(tda.symptom, ','::text, 1) AS "Adversereactions1Name",
	    ''::text AS "Adversereactions2",
	    split_part(tda.symptom, ','::text, 2) AS "Adversereactions2Name",
	    ''::text AS "Adversereactions3",
	    split_part(tda.symptom, ','::text, 3) AS "Adversereactions3Name",
	    ''::text AS "AdverseReactions4",
	    split_part(tda.symptom, ','::text, 4) AS "Adversereactions4Name",
	    ''::text AS "Adversereactions5",
	    split_part(tda.symptom, ','::text, 5) AS "Adversereactions5Name",
	    ''::text AS "Adversereactions6",
	    split_part(tda.symptom, ','::text, 6) AS "Adversereactions6Name",
	    tda.note as "Remark",
	    case when tda.record_date != '' then  ((tda.record_date::text || ' '::text) || tda.record_time::text)::timestamp without time zone else null end AS "Makedatetime",
	    'Inactive' as "Status",
	    tda.track_date || ' ' || tda.track_time AS "InactiveDateTime",
	    e.employee_code as "InactiveByUserCode" ,
	    e.prename || e.firstname || ' ' || e.lastname as "InactiveByUserNameTH" ,
	    e.intername as "InactiveByUserNameEN" 
FROM 	track_drug_allergy tda
	    LEFT JOIN patient p ON tda.patient_id::text = p.patient_id::text
	    left join employee e on tda.track_actor = e.employee_id 
--where 	tda.patient_id  in (select v.patient_id from visit v where v.visit_date = '2024-01-01')
)da
--limit 10