select 'PLR' as "BU"
, p.patient_id as "PatientID"
, os.or_location_id as "FacilityRmsNo"
, or2.or_number as "RequestNo"
, or2.registered_date ||' '|| or2.registered_time as "EntryDateTime"
,get_all_physician_from_op_reg(or2.op_registered_id,'SG')|| (CASE WHEN get_all_physician_from_op_reg(or2.op_registered_id,'0008') = '' THEN '' ELSE ', '||get_all_physician_from_op_reg(or2.op_registered_id,'0008') END) as surgeon
, os.set_doctor_eid as "RequestDoctorCode"
, e.prename || e.firstname ||' '|| e.lastname  as "RequestDoctorNameTH"
, e.intername as "RequestDoctorNameEN"
, vp.plan_code as "RightCode"
, p2.description as "RightNameTH"
, '' as "RightNameEN"
, or2.base_op_room_id as "HNORRmsNo"
, bor.description as "HNORRmsNoNameTH"
, '' as "HNORRmsNoNameEN"
, os.refrain_food_date ||' '|| os.refrain_food_time as "NPODateTime"
, os.op_appoint_date ||' '|| os.op_appoint_time as "AttendDateTime"
, os.accept_date ||' '|| os.accept_time as "ORConfirmDateTime"
, '0' as "PrivateCase"
, os.fix_op_status_id as "ORCaseType"
, bot.description as "ORClassifiedType"
, '' as "ORVisitType"
, '0' as "HoldRequest"
, os.op_appoint_date || ' ' || os.op_appoint_time as "ORBeginDateTimePlan"
, (os.op_appoint_date || ' ' || os.op_appoint_time)::timestamp + (((os.estimate_hour::int * 60) + (os.estimate_minute::int)) || ' minute')::interval as "ORFinishDateTimePlan"
, or2.start_date ||' '|| or2.start_time as "ORBeginDateTimeActual"
, or2.finish_date ||' '|| or2.finish_time as "ORFinishDateTimeActual"
, '' as "AnesBeginDateTimePlan"
, '' as "AnesFinishDateTimePlan"
, or2.start_anes_date ||' '|| or2.start_anes_time as "AnesBeginDateTimeActual"
, or2.finish_anes_date ||' '|| or2.finish_anes_time as "AnesFinishDateTimeActual"
, osd.diagnosis_name as "PreDiagMemo"
, oso.operation_name as "ICDCmMemo"
, '' as "ORPostureCode"
, '' as "ORPostureNameTH"
, '' as "ORPostureNameEN"
, ord.icd10_code as "ORICDGroupCode"
, ord.diagnosis_name as "ORICDGroupNameTH"
, ord.description as "ORICDGroupNameEN"
, oro.icd9_code as "ORICDCmGroupCode"
, oro.operation_name as "ORICDCMGroupNameTH"
, oro.description as "ORICDCMGroupNameEN"
, or2.base_op_clinic_id as "ORSpecialty"
, boc.description as "ORSpecialtyNameTH"
, '' as "ORSpecialtyNameEN"
, '' as "ORWithAnesType"
, '' as "ORReOperationReasonCode"
, '' as "ORReOperationReasonNameTH"
, '' as "ORReOperationReasonNameEN"
, '' as "ORResultCode"
, '' as "ORResultNameTH"
, '' as "ORResultNameEN"
, '' as "CxlDateTime"
, '' as "CxlByUserCode"
, '' as "CxlByUserNameTH"
, '' as "CxlByUserNameEN"
, '' as "CxlReasonCode"
, '' as "CxlReasonNameTH"
, '' as "CxlReasonNameEN"
, '' as "AnesPhysicianCode1"
, '' as "AnesPhysicianNameTH1"
, '' as "AnesPhysicianNameEN1"
, '' as "AnesPhysicianCode2"
, '' as "AnesPhysicianNameTH2"
, '' as "AnesPhysicianNameEN2"
, '' as "AnesNurseCode"
, '' as "AnesNurseNameTH"
, '' as "AnesNurseNameEN"
, '' as "ORPreMedicationCode1"
, '' as "ORPreMedicationNameTH1"
, '' as "ORPreMedicationNameEN1"
, '' as "ORPreMedicationCode2"
, '' as "ORPreMedicationNameTH2"
, '' as "ORPreMedicationNameEN2"
, '' as "ORPreMedicationCode3"
, '' as "ORPreMedicationNameTH3"
, '' as "ORPreMedicationNameEN3"
, '' as "ORPreOpProblemCode1"
, '' as "ORPreOpProblemNameTH1"
, '' as "ORPreOpProblemNameEN1"
, '' as "ORPreOpProblemCode2"
, '' as "ORPreOpProblemNameTH2"
, '' as "ORPreOpProblemNameEN2"
, '' as "ORPreOpProblemCode3"
, '' as "ORPreOpProblemNameTH3"
, '' as "ORPreOpProblemNameEN3"
, '' as "TypeOfAnesthesia1"
, '' as "TypeOfAnesthesiaNameTH1"
, '' as "TypeOfAnesthesiaNameEN1"
, '' as "TypeOfAnesthesia2"
, '' as "TypeOfAnesthesiaNameTH2"
, '' as "TypeOfAnesthesiaNameEN2"
, '' as "AnesTechniqueCode1"
, '' as "AnesTechniqueNameTH1"
, '' as "AnesTechniqueNameEN1"
, '' as "AnesTechniqueCode2"
, '' as "AnesTechniqueNameTH2"
, '' as "AnesTechniqueNameEN2"
, '' as "AnesTechniqueCode3"
, '' as "AnesTechniqueNameTH3"
, '' as "AnesTechniqueNameEN3"
, '' as "AnesTechniqueCode4"
, '' as "AnesTechniqueNameTH4"
, '' as "AnesTechniqueNameEN4"
, '' as "HNORReverseType"
, '' as "AnesReasonCode"
, '' as "AnesReasonNameTH"
, '' as "AnesReasonNameEN"
, '' as "ORPostOPComplicationCode1"
, '' as "ORPostOPComplicationNameTH1"
, '' as "ORPostOPComplicationNameEN1"
, '' as "ORPostOPComplicationCode2"
, '' as "ORPostOPComplicationNameTH2"
, '' as "ORPostOPComplicationNameEN2"
, '' as "ORPostOPComplicationCode3"
, '' as "ORPostOPComplicationNameTH3"
, '' as "ORPostOPComplicationNameEN3"
, '' as "ORInductionDrugCode1"
, '' as "ORInductionDrugNameTH1"
, '' as "ORInductionDrugNameEN1"
, '' as "ORInductionDrugCode2"
, '' as "ORInductionDrugNameTH2"
, '' as "ORInductionDrugNameEN2"
, '' as "ORInductionDrugCode3"
, '' as "ORInductionDrugNameTH3"
, '' as "ORInductionDrugNameEN3"
, '' as "ORInductionDrugCode4"
, '' as "ORInductionDrugNameTH4"
, '' as "ORInductionDrugNameEN4"
, '' as "ORIntubationCode"
, '' as "ORIntubationNameTH"
, '' as "ORIntubationNameEN"
, '' as "ORMaintenanceDrugCode"
, '' as "ORMaintenanceDrugNameTH"
, '' as "ORMaintenanceDrugNameEN"
, '' as "ORPersonWorkingGroupNo"
, or2.pre_diagnosis as "PreDiagMemo"
, '' as "ICDCmMemo"
, os.note as "Remarks"
from visit v 
left join patient p on p.patient_id = v.patient_id 
left join op_registered or2 on or2.visit_id = v.visit_id 
left join op_set os on os.op_registered_id = or2.op_registered_id
left join employee e on os.set_doctor_eid = e.employee_id
left join visit_payment vp on vp.visit_id = v.visit_id and vp.priority = '1'
left join plan p2 on p2.plan_id = vp.plan_id 
left join op_registered_diagnosis ord on ord.op_registered_id = or2.op_registered_id 
left join op_registered_operation oro on oro.op_registered_id = or2.op_registered_id
left join base_op_type bot on bot.base_op_type_id = or2.base_op_type_id
left join base_op_room bor on bor.base_op_room_id = or2.base_op_room_id
left join base_op_clinic boc on boc.base_op_clinic_id = or2.base_op_clinic_id 
left join op_set_operation oso on oso.op_set_id = os.op_set_id 
left join op_set_diagnosis osd on osd.op_set_id = os.op_set_id 
where or2.registered_date between '$P!{dBeginDate}' and '$P!{dEndDate}'
--where v.visit_id = '520110404263139001'
--and or2.active = '1'











