select top 10 
'PT2' as 'BU'
,HN as 'PatientID'
,HN as 'HN'
,case when HNPatientMsgType = 0 then 'None'
	  when HNPatientMsgType = 1 then 'All'
	  when HNPatientMsgType = 2 then 'Reception'
	  when HNPatientMsgType = 3 then 'All_Cashier'
	  when HNPatientMsgType = 4 then 'OPD_Cashier'
	  when HNPatientMsgType = 5 then 'IPD_Cashier'
	  when HNPatientMsgType = 6 then 'Diag_Room'
	  when HNPatientMsgType = 7 then 'Social_Hx'
	  when HNPatientMsgType = 8 then 'Family_Hx'
	  when HNPatientMsgType = 9 then 'Vacination'
	  when HNPatientMsgType = 10 then 'Allergic'
	  when HNPatientMsgType = 11 then 'Chronic'
	  when HNPatientMsgType = 12 then 'Past_History'
	  when HNPatientMsgType = 13 then 'Pharmacy'
	  when HNPatientMsgType = 14 then 'Xray'
	  when HNPatientMsgType = 15 then 'Lab'
	  when HNPatientMsgType = 16 then 'Cashier_to_Cashier'
	  when HNPatientMsgType = 17 then 'OR_to_OR'
	  when HNPatientMsgType = 18 then 'Nutrition'
	  when HNPatientMsgType = 19 then 'Current_Medication'
	  when HNPatientMsgType = 20 then 'Medication_Problem'
	  when HNPatientMsgType = 21 then 'Addition_Caution'
	  when HNPatientMsgType = 22 then 'Service_Purpose'
	  when HNPatientMsgType = 23 then 'PT'
	  end	as 'MessageType'
,RemarksMemo as 'Message'
,LastUpdateDateTime as 'EntryDateTime'
,EntryByUserCode --แก้ไขวันที่ 24/02/2568
,dbo.sysconname(EntryByUserCode,10031,2) as 'EntryByUserNameTH' --เพิ่มวันที่ 24/02/2568
,dbo.sysconname(EntryByUserCode,10031,1) as 'EntryByUserNameEN' --เพิ่มวันที่ 24/02/2568
,'Active' as 'Status'
,'' as 'EffectiveDateTimeFrom'
,'' as 'EffectiveDateTimeTo'
		from HNPAT_MSG
		order by right(HN,2) desc