

select
'PLR' as "BU"
, i.item_code as "LabCode"
, i.common_name as "LabNameTH"
, i.common_name_en as "LabNameEN"
, '' as "GroupOfLabCode"
, '' as "GroupOfLabNameTH"
, '' as "GroupOfLabNameEN"
, '' as "ChartColour"
, '' as "ChartColourNameTH"
, '' as "ChartColourNameEN"
, '' as "Symptomatic"
, '' as "SymptomaticNameTH"
, '' as "SymptomaticNameEN"
, i.base_specimen_id as "Specimen"
, bs.description as "SpecimenNameTH"
, '' as "SpecimenNameEN"
, '' as "HNActivityOPD"
, '' as "HNActivityOPDNameTH"
, '' as "HNActivityOPDNameEN"
, '' as "HNActivityIPD"
, '' as "HNActivityIPDNameTH"
, '' as "HNActivityIPDNameEN"
, '' as "ResultUnitCode"
, '' as "ResultUnitNameTH"
, '' as "ResultUnitNameEN"
, '' as "NormalLabCommentCode"
, '' as "NormalLabCommentNameTH"
, '' as "NormalLabCommentNameEN"
, i.base_lab_type_id as "FacilityRMSNo"
, '' as "FacilityRMSNoNameTH"
, blt.description as "FacilityRMSNoNameEN"
, '' as "LabSpecimenMethod"
, '' as "LabSpecimenMethodNameTH"
, '' as "LabSpecimenMethodNameEN"
, '' as "Abbreviate"
, '' as "DoctorGroup"
, '' as "DoctorGroupNameTH"
, '' as "DoctorGroupNameEN"
, '' as "DefaultRequestQty"
, '' as "DefaultOutsideLab"
, '' as "DefaultOutsideLabNameTH"
, '' as "DefaultOutsideLabNameEN"
, '' as "CheckUpHNActivity"
, '' as "CheckUpHNActivityNameTH"
, '' as "CheckUpHNActivityNameEN"
, '' as "Gender"
, '' as "GenderNameTH"
, '' as "GenderNameEN"
, '' as "LabLockSpecimenType"
, '' as "LabLockSpecimenTypeName"
, '' as "AutoSlectAllSpecimen"
, i.base_lab_type_id as "TypeOfLabCode"
, blt.description as "TypeOfLabName"
, '' as "LabResultStyle"
, '' as "LabResultStyleName"
, '' as "NoDecimalResult"
, '' as "MustBeFigure"
, '' as "SingelResultValueType"
, '' as "SingelResultValueTypeName"
, i.secret_status as "AutoHideResultType"
, '' as "AutoHideResultTypeName"
, '' as "QtyToSplit"
, '' as "AdditionRequestLabCode1"
, '' as "AdditionRequestLabCode1NameTH"
, '' as "AdditionRequestLabCode1NameEN"
, '' as "AdditionRequestLabCode2"
, '' as "AdditionRequestLabCode2NameTH"
, '' as "AdditionRequestLabCode2NameEN"
, '' as "AdditionRequestLabCode3"
, '' as "AdditionRequestLabCode3NameTH"
, '' as "AdditionRequestLabCode3NameEN"
, '' as "AdditionRequestLabCode4"
, '' as "AdditionRequestLabCode4NameTH"
, '' as "AdditionRequestLabCode4NameEN"
, '' as "AdditionRequestLabCode5"
, '' as "AdditionRequestLabCode5NameTH"
, '' as "AdditionRequestLabCode5NameEN"
, '' as "AdditionRequestLabCode6"
, '' as "AdditionRequestLabCode6NameTH"
, '' as "AdditionRequestLabCode6NameEN"
, '' as "AppmntProcedureMethod"
, '' as "AppmntProcedureMethodNameTH"
, '' as "AppmntProcedureMethodNameEN"
, '' as "LabNormalValueType"
, '' as "LabNormalValueTypeName"
, '' as "FinalResultFromType"
, '' as "FinalResultFromTypeName"
, '' as "TimeToBeDoneText"
, '' as "ResultOnRequest"
, '' as "RequestWithRemark"
, '' as "NeverChargeOnRequest"
, '' as "ShowHighPriceWarning"
, case when i.edit_price = '1' then '1' else '0' end as "OpenPrice"
, '' as "NeverShowUpOnHelp"
, '' as "CanBeZeroPrice"
, '' as "EntryWantedDate"
, case when i.active = '0' then '1' else '0' end as "OffCode"
, '' as "InfectionControl"
, '' as "OneTimeUse"
, '' as "NeverStatistic"
, '' as "HostComputerAlwaysCheckNormalValue"
from item i 
left join base_specimen bs on bs.base_specimen_id = i.base_specimen_id
left join base_lab_type blt on blt.base_lab_type_id = i.base_lab_type_id
where i.fix_item_type_id = '1'
union all 
select
'PLR' as "BU"
, tlt.template_lab_test_id as "LabCode"
, tlt."name" as "LabNameTH"
, '' as "LabNameEN"
, '' as "GroupOfLabCode"
, '' as "GroupOfLabNameTH"
, '' as "GroupOfLabNameEN"
, '' as "ChartColour"
, '' as "ChartColourNameTH"
, '' as "ChartColourNameEN"
, '' as "Symptomatic"
, '' as "SymptomaticNameTH"
, '' as "SymptomaticNameEN"
, '' as "Specimen"
, '' as "SpecimenNameTH"
, '' as "SpecimenNameEN"
, '' as "HNActivityOPD"
, '' as "HNActivityOPDNameTH"
, '' as "HNActivityOPDNameEN"
, '' as "HNActivityIPD"
, '' as "HNActivityIPDNameTH"
, '' as "HNActivityIPDNameEN"
, '' as "ResultUnitCode"
, '' as "ResultUnitNameTH"
, tlt.unit_text as "ResultUnitNameEN"
, '' as "NormalLabCommentCode"
, '' as "NormalLabCommentNameTH"
, '' as "NormalLabCommentNameEN"
, '' as "FacilityRMSNo"
, '' as "FacilityRMSNoNameTH"
, '' as "FacilityRMSNoNameEN"
, '' as "LabSpecimenMethod"
, '' as "LabSpecimenMethodNameTH"
, '' as "LabSpecimenMethodNameEN"
, '' as "Abbreviate"
, '' as "DoctorGroup"
, '' as "DoctorGroupNameTH"
, '' as "DoctorGroupNameEN"
, '' as "DefaultRequestQty"
, '' as "DefaultOutsideLab"
, '' as "DefaultOutsideLabNameTH"
, '' as "DefaultOutsideLabNameEN"
, '' as "CheckUpHNActivity"
, '' as "CheckUpHNActivityNameTH"
, '' as "CheckUpHNActivityNameEN"
, tlnv.fix_lab_normal_value_type_id as "Gender"
, case when tlnv.fix_lab_normal_value_type_id = '1' then 'ผู้ป่วยทุกประเภท'
when tlnv.fix_lab_normal_value_type_id = '2' then 'ผู้ป่วยเด็ก'
when tlnv.fix_lab_normal_value_type_id = '3' then 'ผู้ป่วยผู้ชาย'
when tlnv.fix_lab_normal_value_type_id = '4' then 'ผู้ป่วยผู้หญิง'
when tlnv.fix_lab_normal_value_type_id = '5' then 'ผู้ป่วยชรา' else 'None'end as "GenderNameTH"
, '' as "GenderNameEN"
, '' as "LabLockSpecimenType"
, '' as "LabLockSpecimenTypeName"
, '' as "AutoSlectAllSpecimen"
, '' as "TypeOfLabCode"
, '' as "TypeOfLabName"
, tlt.fix_lab_test_type_id as "LabResultStyle"
, fltt.description as "LabResultStyleName"
, '' as "NoDecimalResult"
, '' as "MustBeFigure"
, '' as "SingelResultValueType"
, '' as "SingelResultValueTypeName"
, '' as "AutoHideResultType"
, '' as "AutoHideResultTypeName"
, '' as "QtyToSplit"
, '' as "AdditionRequestLabCode1"
, '' as "AdditionRequestLabCode1NameTH"
, '' as "AdditionRequestLabCode1NameEN"
, '' as "AdditionRequestLabCode2"
, '' as "AdditionRequestLabCode2NameTH"
, '' as "AdditionRequestLabCode2NameEN"
, '' as "AdditionRequestLabCode3"
, '' as "AdditionRequestLabCode3NameTH"
, '' as "AdditionRequestLabCode3NameEN"
, '' as "AdditionRequestLabCode4"
, '' as "AdditionRequestLabCode4NameTH"
, '' as "AdditionRequestLabCode4NameEN"
, '' as "AdditionRequestLabCode5"
, '' as "AdditionRequestLabCode5NameTH"
, '' as "AdditionRequestLabCode5NameEN"
, '' as "AdditionRequestLabCode6"
, '' as "AdditionRequestLabCode6NameTH"
, '' as "AdditionRequestLabCode6NameEN"
, '' as "AppmntProcedureMethod"
, '' as "AppmntProcedureMethodNameTH"
, '' as "AppmntProcedureMethodNameEN"
, tlnv.fix_lab_normal_value_type_id as "LabNormalValueType"
, flnvt.description as "LabNormalValueTypeName"
, '' as "FinalResultFromType"
, '' as "FinalResultFromTypeName"
, '' as "TimeToBeDoneText"
, '' as "ResultOnRequest"
, '' as "RequestWithRemark"
, '' as "NeverChargeOnRequest"
, '' as "ShowHighPriceWarning"
, '0' as "OpenPrice"
, '' as "NeverShowUpOnHelp"
, '' as "CanBeZeroPrice"
, '' as "EntryWantedDate"
, '0' as "OffCode"
, '' as "InfectionControl"
, '' as "OneTimeUse"
, '' as "NeverStatistic"
, '' as "HostComputerAlwaysCheckNormalValue"
from template_lab_test tlt
left join template_lab_normal_value tlnv on tlt.template_lab_test_id = tlnv.template_lab_test_id
left join fix_lab_test_type fltt on fltt.fix_lab_test_type_id = tlt.fix_lab_test_type_id
left join fix_lab_normal_value_type flnvt on flnvt.fix_lab_normal_value_type_id = tlnv.template_lab_normal_value_id

