select
		  'PTP' as 'BU'
		, ptr.HN as 'PatientID'
		, '' as 'FacilityRmsNo'
		, ptp.REQUESTNO as 'RequestNo'
		, ptp.PTMODE as 'PTModeCode'
		, dbo.sysconname(ptp.PTMODE,20104,2) as 'PTModeNameTH'
		, dbo.sysconname(ptp.PTMODE,20104,1) as 'PTModeNameEN'
		, ptp.CHARGECODE as 'HNActivityCode'
		, dbo.sysconname(ptp.CHARGECODE,20023,2) as 'HNActivityNameTH'
		, dbo.sysconname(ptp.CHARGECODE,20023,1) as 'HNActivityNameEN'
		, ptp.ENTRYDATETIME as 'ChargeDateTime'
		, ptp.VISITDATE as 'ChargeVisitDate'
		, '' as 'IRNo'
		, ptp.VN as 'ChargeVN'
		, ptp.AN as 'ChargeAN'
		, ptr.RIGHTCODE as 'RightCode'
		, dbo.sysconname(ptr.RIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(ptr.RIGHTCODE,20019,1) as 'RightNameEN'
		, ptp.AMT as 'ChargeAmt'
		,case when ptp.TYPEOFCHARGE = 0 then 'None'
			  when ptp.TYPEOFCHARGE = 1 then 'Free'
			  when ptp.TYPEOFCHARGE = 2 then 'Refund'
			  when ptp.TYPEOFCHARGE = 3 then 'Cxl'
			  when ptp.TYPEOFCHARGE = 4 then 'Usage_FOC'
			  when ptp.TYPEOFCHARGE = 5 then 'Never_Charge'
			  when ptp.TYPEOFCHARGE = 6 then 'Adjust'
			  when ptp.TYPEOFCHARGE = 7 then 'Return_Usage_FOC'
		 end as 'ChargeType'
		, ptp.RECEIVEBYUSERCODE as 'EntryByUserCode'
		, dbo.sysconname(ptp.RECEIVEBYUSERCODE,10000,2) as 'EntryByUserNameTH'
		, dbo.sysconname(ptp.RECEIVEBYUSERCODE,10000,1) as 'EntryByUserNameEN'
		, '' as 'VoidByUserCode'
		, '' as 'VoidByUserNameTH'
		, '' as 'VoidByUserNameEN'
		, '' as 'VoidDateTime'
		, '' as 'VoidRemarks'
		, ptp.CHARGEVOUCHERNO as 'ChargeVoucherNo'
		, ptp.REMARKSMEMO as 'Remarks'
				from PTPAYMENT ptp
				left join PTREQUEST ptr on ptp.REQUESTNO=ptr.REQUESTNO
				where ptp.REQUESTNO = '6710-0007'
