select
		  'PTP' as 'BU'
		, ptr.HN as 'PatientID'
		, '' as 'FacilityRmsNo'
		, pta.REQUESTNO as 'RequestNo'
		, '' as 'PTModeSuffixSmall'
		, pta.PTMODE as 'PTModeCode'
		, dbo.sysconname(pta.PTMODE,20104,2) as 'PTModeNameTH'
		, dbo.sysconname(pta.PTMODE,20104,1) as 'PTModeNameEN'
		, pta.PTSYSTEM as 'PTSystemCode'
		, '' as 'PTSystemNameTH'
		, '' as 'PTSystemNameEN'
		, pta.ORGAN as 'OrganCode1'
		, dbo.sysconname(pta.ORGAN,20053,2) as 'OrganNameTH1'
		, dbo.sysconname(pta.ORGAN,20053,1) as 'OrganNameEN1'
		, pta.ORGAN2 as 'OrganCode2'
		, dbo.sysconname(pta.ORGAN2,20053,2) as 'OrganNameTH2'
		, dbo.sysconname(pta.ORGAN2,20053,1) as 'OrganNameEN2'
		, pta.ORGAN3 as 'OrganCode3'
		, dbo.sysconname(pta.ORGAN3,20053,2) as 'OrganNameTH3'
		, dbo.sysconname(pta.ORGAN3,20053,1) as 'OrganNameEN3'
		, pta.ORGANPOSITION as 'OrganPosition1'
		, dbo.sysconname(pta.ORGANPOSITION,20054,2) as 'OrganPositionNameTH1'
		, dbo.sysconname(pta.ORGANPOSITION,20054,1) as 'OrganPositionNameEN1'
		, pta.ORGANPOSITION2 as 'OrganPosition2'
		, dbo.sysconname(pta.ORGANPOSITION2,20054,2) as 'OrganPositionNameTH2'
		, dbo.sysconname(pta.ORGANPOSITION2,20054,1) as 'OrganPositionNameEN2'
		, pta.ORGANPOSITION3 as 'OrganPosition3'
		, dbo.sysconname(pta.ORGANPOSITION3,20054,2) as 'OrganPositionNameTH3'
		, dbo.sysconname(pta.ORGANPOSITION3,20054,1) as 'OrganPositionNameEN3'
		, pta.PHYSIOTHERAPISTDOCTOR as 'PTTherapistCode1'
		, dbo.CutSortChar(doc1.THAINAME) as 'PTTherapistNameTH1'
		, dbo.CutSortChar(doc1.ENGLISHNAME) as 'PTTherapistNameEN1'
		, pta.PHYSIOTHERAPISTDOCTOR2 as 'PTTherapistCode2'
		, dbo.CutSortChar(doc2.THAINAME) as 'PTTherapistNameTH2'
		, dbo.CutSortChar(doc2.ENGLISHNAME) as 'PTTherapistNameEN2'
		, pta.PHYSIOTHERAPISTDOCTOR3 as 'PTTherapistCode3'
		, dbo.CutSortChar(doc3.THAINAME) as 'PTTherapistNameTH3'
		, dbo.CutSortChar(doc3.ENGLISHNAME) as 'PTTherapistNameEN3'
		, '' as 'RegisterDateTime'
		, pta.STARTDATETIME as 'StartDateTime'
		, pta.FINISHDATETIME as 'FinishDateTime'
		, pta.ENTRYDATETIME as 'EntryDateTime'
		, '' as 'ChargeType'
		, pta.ATWARD as 'AtWard'
		, '' as 'IpdOpdType'
		, pta.RIGHTCODE as 'RightCode'
		, dbo.sysconname(pta.RIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(pta.RIGHTCODE,20019,1) as 'RightNameEN'
		, pta.QTY as 'Qty'
				from PTATTEND pta
				left join PTREQUEST ptr on pta.REQUESTNO=ptr.REQUESTNO
				left join HNDOCTOR doc1 on pta.PHYSIOTHERAPISTDOCTOR=doc1.DOCTOR
				left join HNDOCTOR doc2 on pta.PHYSIOTHERAPISTDOCTOR2=doc2.DOCTOR
				left join HNDOCTOR doc3 on pta.PHYSIOTHERAPISTDOCTOR3=doc3.DOCTOR
