select
		  'PTP' as 'BU'
		, ptr.HN as 'PatientID'
		, '' as 'FacilityRmsNo'
		, ptu.REQUESTNO as 'RequestNo'
		, ptu.SUFFIX as 'SuffixTiny'
		, ptu.MAKEDATETIME as 'EntryDateTime'
		, ptu.STORE as 'Store'
		, dbo.sysconname(ptu.STORE,40010,2) as 'StoreNameTH'
		, dbo.sysconname(ptu.STORE,40010,1) as 'StoreNameEN'
		, ptu.STOCKCODE as 'StockCode'
		, dbo.Stockname(ptu.STOCKCODE,2) as 'StockNameTH'
		, dbo.Stockname(ptu.STOCKCODE,1) as 'StockNameEN'
		, ptu.UNITCODE as 'UnitCode'
		, dbo.sysconname(ptu.UNITCODE,40016,2) as 'UnitNameTH'
		, dbo.sysconname(ptu.UNITCODE,40016,1) as 'UnitNameEN'
		, '' as 'ReverseDrugControl'
		, ptu.QTY as 'Qty'
		, ptu.UNITPRICE as 'UnitPrice'
		, ptu.COST as 'Cost'
		, ptu.AMT as 'ChargeAmt'
		, ptr.RIGHTCODE as 'RightCode'
		, dbo.sysconname(ptr.RIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(ptr.RIGHTCODE,20019,1) as 'RightNameEN'
		, ptu.CHARGECODE as 'HNActivityCode'
		, dbo.sysconname(ptu.CHARGECODE,20023,2) as 'HNActivityNameTH'
		, dbo.sysconname(ptu.CHARGECODE,20023,1) as 'HNActivityNameEN'
		, ptu.CHARGEDATETIME as 'ChargeDateTime'
		,case when ptu.TYPEOFCHARGE = 0 then 'None'
			  when ptu.TYPEOFCHARGE = 1 then 'Free'
			  when ptu.TYPEOFCHARGE = 2 then 'Refund'
			  when ptu.TYPEOFCHARGE = 3 then 'Cxl'
			  when ptu.TYPEOFCHARGE = 4 then 'Usage_FOC'
			  when ptu.TYPEOFCHARGE = 5 then 'Never_Charge'
			  when ptu.TYPEOFCHARGE = 6 then 'Adjust'
			  when ptu.TYPEOFCHARGE = 7 then 'Return_Usage_FOC'
		 end as 'ChargeType'
		, '' as 'IpdOpdType'
		, ptu.ENTRYBYUSERCODE as 'EntryByUserCode'
		, dbo.sysconname(ptu.ENTRYBYUSERCODE,10000,2) as 'EntryByUserNameTH'
		, dbo.sysconname(ptu.ENTRYBYUSERCODE,10000,1) as 'EntryByUserNameEN'
		, ptu.REMARKS as 'RemarksMemo'
		, '' as 'ComputerLocation'
		, '' as 'ImportParStock'
				from PTUSAGE ptu
				left join PTREQUEST ptr on ptu.REQUESTNO=ptr.REQUESTNO