select
		  'PTP' as 'BU'
		, ptr.HN as 'PatientID'
		, '' as 'FacilityRmsNo'
		, ptm.REQUESTNO as 'RequestNo'
		, '' as 'PTModeSuffixSmall'
		, ptm.PTMODE as 'PTModeCode'
		, dbo.sysconname(ptm.PTMODE,20104,2) as 'PTModeNameTH'
		, dbo.sysconname(ptm.PTMODE,20104,1) as 'PTModeNameEN'
		, ptm.NOOFVISITTOBEDONE as 'NoOfVisitTobeDone'
		, '' as 'UnitPrice'
		, '' as 'ChargeAmt'
		, '' as 'PaidFromChargeAmt'
		, '' as 'ChargeDateTime'
		, '' as 'ChargeType'
		, ptm.PTSYSTEM as 'PTSystemCode'
		, '' as 'PTSystemNameTH'
		, '' as 'PTSystemNameEN'
		, ptm.ORGAN as 'OrganCode'
		, dbo.sysconname(ptm.ORGAN,20053,2) as 'OrganNameTH'
		, dbo.sysconname(ptm.ORGAN,20053,1) as 'OrganNameEN'
		, ptm.ORGANPOSITION as 'OrganPosition'
		, dbo.sysconname(ptm.ORGANPOSITION,20054,2) as 'OrganPositionNameTH'
		, dbo.sysconname(ptm.ORGANPOSITION,20054,1) as 'OrganPositionNameEN'
		, ptm.PHYSIOTHERAPISTDOCTOR as 'PTTherapistCode'
		, dbo.CutSortChar(doc.THAINAME) as 'PTTherapistNameTH'
		, dbo.CutSortChar(doc.ENGLISHNAME) as 'PTTherapistNameEN'
		, ptm.ATWARD as 'AtWard'
		, ptm.MINUTEPERVISIT as 'MinutePerVisit'
		, '' as 'VoidDateTime'
		, ptm.REMARKSMEMO as 'Remarks'
				from PTMODE ptm
				left join PTREQUEST ptr on ptm.REQUESTNO=ptr.REQUESTNO
				left join HNDOCTOR doc on ptm.PHYSIOTHERAPISTDOCTOR=doc.DOCTOR