select
		 'PTP' as 'BU'
		, ptr.HN as 'PatientID'
		, '' as 'FacilityRmsNo'
		, pts.REQUESTNO as 'RequestNo'
		, pts.ENTRYDATETIME as 'DiagDateTime'
		, pts.ICDCODE as 'PTDiagCode'
		, icd.THAINAME as 'PTDiagNameTH'
		, icd.ENGLISHNAME as 'PTDiagNameEN'
		,'' as 'PTSystemCode'
		,'' as 'PTSystemNameTH'
		,'' as 'PTSystemNameEN'
		,'' as 'PTStopReasonCode'
		,'' as 'PTStopReasonNameTH'
		,'' as 'PTStopReasonNameEN'
		, pts.ORGAN as 'OrganCode1'
		, dbo.sysconname(pts.ORGAN,20053,2) as 'OrganNameTH1'
		, dbo.sysconname(pts.ORGAN,20053,1) as 'OrganNameEN1'
		, pts.ORGAN2 as 'OrganCode2'
		, dbo.sysconname(pts.ORGAN2,20053,2) as 'OrganNameTH2'
		, dbo.sysconname(pts.ORGAN2,20053,1) as 'OrganNameEN2'
		, pts.ORGAN3 as 'OrganCode3'
		, dbo.sysconname(pts.ORGAN3,20053,2) as 'OrganNameTH3'
		, dbo.sysconname(pts.ORGAN3,20053,1) as 'OrganNameEN3'
		, pts.ORGANPOSITION as 'OrganPosition1'
		, dbo.sysconname(pts.ORGANPOSITION,20054,2) as 'OrganPositionNameTH1'
		, dbo.sysconname(pts.ORGANPOSITION,20054,1) as 'OrganPositionNameEN1'
		, pts.ORGANPOSITION2 as 'OrganPosition2'
		, dbo.sysconname(pts.ORGANPOSITION2,20054,2) as 'OrganPositionNameTH2'
		, dbo.sysconname(pts.ORGANPOSITION2,20054,1) as 'OrganPositionNameEN2'
		, pts.ORGANPOSITION3 as 'OrganPosition3'
		, dbo.sysconname(pts.ORGANPOSITION3,20054,2) as 'OrganPositionNameTH3'
		, dbo.sysconname(pts.ORGANPOSITION3,20054,1) as 'OrganPositionNameEN3'
		, pts.ENTRYDATETIME as 'EntryDateTime'
		, pts.PHYSIOTHERAPISTDOCTOR as 'PTTherapistCode'
		, dbo.CutSortChar(doc.THAINAME) as 'PTTherapistNameTH'
		, dbo.CutSortChar(doc.ENGLISHNAME) as 'PTTherapistNameEN'
		, pts.REFERTOHOSPITAL as 'RefToHospital'
		, dbo.sysconname(pts.REFERTOHOSPITAL,20010,2) as 'RefToHospitalNameTH'
		, dbo.sysconname(pts.REFERTOHOSPITAL,20010,1) as 'RefToHospitalNameEN'
		, ptr.REFERTOTYPE as 'RefToCode'
		, dbo.sysconname(ptr.REFERTOTYPE,20060,2) as 'RefToNameTH'
		, dbo.sysconname(ptr.REFERTOTYPE,20060,1) as 'RefToNameEN'
		, ptr.REFERTOREMARKS as 'RefToRefNo'
		, pts.FOLLOWUP as 'FollowUp'
		, '' as 'FacilityResultType'
		, pts.PTTREATMENTTYPE as 'HNPTTreatmentType'
		, pts.PTSTATUSTYPE as 'HNPTStatusType'
		, '' as 'IpdOpdType'
		, pts.REMARKSMEMO as 'RemarksMemo'
		, '' as 'ICDCmCode'
		, '' as 'ICDCmNameTH'
		, '' as 'ICDCmNameEN'
				from PTSUMMARY pts
				left join PTREQUEST ptr on pts.REQUESTNO=ptr.REQUESTNO
				left join ICD_MASTER icd on pts.ICDCODE=icd.ICDCODE
				left join HNDOCTOR doc on pts.PHYSIOTHERAPISTDOCTOR=doc.DOCTOR
