select top 10 
		 'PTP' as 'BU'
		, ptr.HN as 'PatientID'
		, '' as 'FacilityRmsNo'
		, ptr.REQUESTNO as 'RequestNo'
		, ptr.ENTRYDATETIME as 'EntryDateTime'
		, ptr.REQUESTDOCTOR as 'RequestDoctor'
		, dbo.CutSortChar(doc.THAINAME) as 'RequestDoctorNameTH'
		, dbo.CutSortChar(doc.ENGLISHNAME) as 'RequestDoctorNameEN'
		, ptr.ALREADYSETTLE as 'HNAlready'
		, ptr.REQUESTDOCTOR as 'PTTherapistCode'
		, dbo.CutSortChar(doc.THAINAME) as 'PTTherapistNameTH'
		, dbo.CutSortChar(doc.ENGLISHNAME) as 'PTTherapistNameEN'
		, '' as 'CaseCloseCode'
		, '' as 'CaseCloseNameTH'
		, '' as 'CaseCloseNameEN'
		, '' as 'CaseCloseDateTime'
		, ptr.PATIENTTYPE as 'PatientType'
		, dbo.sysconname(ptr.PATIENTTYPE,20011,2) as 'PatientTypeNameTH'
		, dbo.sysconname(ptr.PATIENTTYPE,20011,1) as 'PatientTypeNameEN'
		, '' as 'LastAttendDateTime'
		, '' as 'LastChargeDateTime'
		, '' as 'RequestByUserCode'
		, '' as 'RequestByUserNameTH'
		, '' as 'RequestByUserNameEN'
		, ptr.RIGHTCODE as 'RightCode'
		, dbo.sysconname(ptr.RIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(ptr.RIGHTCODE,20019,1) as 'RightNameEN'
		, '' as 'AppointmentNo'
		, '' as 'AppointmentDateTime'
		, ptr.CLINIC as 'Clinic'
		, dbo.sysconname(ptr.CLINIC,20016,2) as 'ClinicNameTH'
		, dbo.sysconname(ptr.CLINIC,20016,1) as 'ClinicNameEN'
		, ptr.WARD as 'Ward'
		, dbo.sysconname(ptr.WARD,20024,2) as 'WardNameTH'
		, dbo.sysconname(ptr.WARD,20024,1) as 'WardNameEN'
		, ptr.REMARKSNAME as 'Remarks'
				from PTREQUEST ptr
				left join HNDOCTOR doc on ptr.REQUESTDOCTOR=doc.DOCTOR