use
SSBHOSPITAL
go

select
		  'PLS' as BU
		, stm.STOCKCODE as StockCode
		, dbo.CutSortChar(stm.THAINAME) as StockNameTH
		, dbo.CutSortChar(stm.ENGLISHNAME) as StockNameEN
		, stm.TREATMENTCODE as TreatmentCode
		, dbo.sysconname(stm.TREATMENTCODE,20051,2) as TreatmentNameTH
		, dbo.sysconname(stm.TREATMENTCODE,20051,1) as TreatmentNameEN
		, '' as GroupOfChargeCode
		, '' as GroupOfChargeNameTH
		, '' as GroupOfChargeNameEN
		, '' as PrePregnantWarningType
		, stm.POISON as PoisonClass
		, dbo.sysconname(stm.POISON,20027,2) as PoisonClassNameTH
		, dbo.sysconname(stm.POISON,20027,1) as PoisonClassNameEN
		, stm.MaxDosePerDayQty as MaxDosePerDayQty
		, stm.MaxDosePerDayUnitCode as MaxDosePerDayUnitCode
		, '' as MaxDosePerDayUnitNameTH
		, '' as MaxDosePerDayUnitNameEN
		, stm.NoDayCanContinueTake as NoDayCanContinueTake
		, stm.NotForPregnantCode as WarningPregnantCode
		, dbo.sysconname(stm.NotForPregnantCode,20683,2) as WarningPregnantNameTH
		, dbo.sysconname(stm.NotForPregnantCode,20683,1) as WarningPregnantNameEN
		, stm.AVAILIABLEFORONLYSEX as AvailableGender
		, '' as AvailableGenderName
		, stm.CANBEZEROPRICE as DrugCanZeroPriceType
		, stm.AUXLABEL1 as AuxLabel1
		, dbo.sysconname(stm.AUXLABEL1,20030,2) as AuxLabel1NameTH
		, dbo.sysconname(stm.AUXLABEL1,20030,1) as AuxLabel1NameEN
		, stm.AUXLABEL2 as AuxLabel2
		, dbo.sysconname(stm.AUXLABEL2,20030,2) as AuxLabel2NameTH
		, dbo.sysconname(stm.AUXLABEL2,20030,1) as AuxLabel2NameEN
		, stm.AUXLABEL3 as AuxLabel3
		, dbo.sysconname(stm.AUXLABEL3,20030,2) as AuxLabel3NameTH
		, dbo.sysconname(stm.AUXLABEL3,20030,1) as AuxLabel3NameEN
		, '' as AuxEnglishMemo
		, '' as AuxLocalMemo
		, '' as DoseType1
		, '' as DoseType1NameTH
		, '' as DoseType1NameEN
		, '' as DoseType2
		, '' as DoseType2NameTH
		, '' as DoseType2NameEN
		, '' as DoseType3
		, '' as DoseType3NameTH
		, '' as DoseType3NameEN
		, '' as DoseUnitCode1
		, '' as DoseUnitCode1NameTH
		, '' as DoseUnitCode1NameEN
		, '' as DoseUnitCode2
		, '' as DoseUnitCode2NameTH
		, '' as DoseUnitCode2NameEN
		, '' as DoseUnitCode3
		, '' as DoseUnitCode3NameTH
		, '' as DoseUnitCode3NameEN
		, stm.PHARMACOINDEX as PharmacoIndex
		, dbo.sysconname(stm.PHARMACOINDEX,20025,2) as PharmacoIndexNameTH
		, dbo.sysconname(stm.PHARMACOINDEX,20025,1) as PharmacoIndexNameEN
		, stm.PHARMACOINDEXSUBCLASS as PharmacoIndexAddition1
		, '' as PharmacoIndexAddition1NameTH
		, '' as PharmacoIndexAddition1NameEN
		, '' as PharmacoIndexAddition2
		, '' as PharmacoIndexAddition2NameTH
		, '' as PharmacoIndexAddition2NameEN
		, '' as PharmacoIndexAddition3
		, '' as PharmacoIndexAddition3NameTH
		, '' as PharmacoIndexAddition3NameEN
		, '' as DoseUnitCodeForWeight
		, '' as DoseUnitCodeForWeightNameTH
		, '' as DoseUnitCodeForWeightNameEN
		, '' as WeightUnitName
		, '' as WeightPerDoseUnit
		, '' as NoDayAgeFrom
		, '' as NoDayAgeTo
		, '' as DoseCode
		, '' as DoseNameTH
		, '' as DoseNameEN
		, '' as DoseFreqCode
		, '' as DoseFreqNameTH
		, '' as DoseFreqNameEN
		, '' as OnlyDoctorGroup
		, '' as OnlyDoctorGroupNameTH
		, '' as OnlyDoctorGroupNameEN
		, '' as DoseQtyCode
		, '' as DoseQtyNameTH
		, '' as DoseQtyNameEN
		, '' as NeverRightGroupCodeList
		, '' as NeverRightGroupCodeListNameTH
		, '' as NeverRightGroupCodeListNameEN
		, '' as MedicineStructureCode
		, '' as MedicineStructureNameTH
		, '' as MedicineStructureNameEN
		, '' as AlwaysGoWithStockCodeList
		, '' as AlwaysGoWithStockCodeListNameTH
		, '' as AlwaysGoWithStockCodeListNameEN
		, '' as AlwaysGoWithStockQtyType
		, stm.ANTIBIOTIC as Antibiotic
		, '' as ValidForNoDayAgeOnly
		, stm.NEVERCONTINUEDRUG as NeverContinueDrug
		, '' as DoseCodeNeverChange
		, '' as AnyAgeSameDose
		, '' as DoseTypeNeverChange
		, '' as DoseUnitCode
				from SSBSTOCK.dbo.STOCK_MASTER stm