select
		  'PLS' as BU
		, stm.STOCKCODE as StockCode
		, dbo.cutsortchar(stm.THAINAME) as StockNameTH
		, dbo.cutsortchar(stm.ENGLISHNAME) as StockNameEN
		, stm.SHORTNAME as ShortName
		, stm.MAINCATEGORY as StockComposeCategory
		, dbo.sysconname(stm.MAINCATEGORY,40011,2) as StockComposeCategoryNameTH
		, dbo.sysconname(stm.MAINCATEGORY,40011,1) as StockComposeCategoryNameEN
		, '' as SmallestUnitCode
		, '' as SmallestUnitNameTH
		, '' as SmallestUnitNameEN
		, stm.FDANO as FDANo
		, stm.GRADECODE as GradeCode
		, dbo.sysconname(stm.GRADECODE,40015,2) as GradeNameTH
		, dbo.sysconname(stm.GRADECODE,40015,1) as GradeNameEN
		, stm.COLOURCODE as ColourCode
		, dbo.sysconname(stm.COLOURCODE,10011,2) as ColourNameTH
		, dbo.sysconname(stm.COLOURCODE,10011,1) as ColourNameEN
		, stm.MAKER as Maker
		, '' as MakerNameTH
		, '' as MakerNameEN
		, stm.Tariff as Tariff
		, stm.ModelCode as ModelCode
		, '' as QCDurationMinutes
		, '' as MinNoDayExpire
		, '' as NoDayLife
		, '' as StockInactiveCode
		, '' as StockInactiveNameTH
		, '' as StockInactiveNameEN
		, '' as PercentageOfOverPO
		, '' as SKNonDrugChargeType
		, '' as DefaultStockActivityCode
		, '' as DefaultStockActivityNameTH
		, '' as DefaultStockActivityNameEN
		, '' as AdditionStatStockCodeColl
		, stm.MakeDateTime as MakeDateTime
		, stm.DeletedDateTime as DeletedDateTime
		, stm.DateLastClose as DateLastClose
		, '' as CreateByUserCode
		, '' as CreateByUserNameTH
		, '' as CreateByUserNameEN
		, stm.SelfProduce as SelfProduce
		, stm.ExpiryDateCheck as ExpiryDateCheck
		, stm.NetPrice as NetPrice
		, stm.NonItem as NonItem
		, '' as Inactive
		, '' as NonVAT
				from SSBSTOCK.dbo.STOCK_MASTER stm