select
		  'PLS' as 'BU'
		, vnm.HN as 'PatientID'
		, convert(varchar,vnd.VISITDATE,112)+convert(varchar,vnd.VN)+convert(varchar,vnd.SUFFIX) as 'VisitID'
		, vnd.VISITDATE as 'VisitDate'
		, vnd.VN as 'VN'
		, vnd.SUFFIX as 'PrescriptionNo'
		, vnd.SUBSUFFIX as 'Suffix'
		, vnp.CLINIC as 'ClinicCode'
		, dbo.sysconname(vnp.CLINIC,20016,2) as 'ClinicNameTH'
		, dbo.sysconname(vnp.CLINIC,20016,1) as 'ClinicNameEN'
		, vnd.DIAGDATETIME as 'DiagDateTime'
		--, '' as 'DiagnosisRecordType'
		--, '' as 'DiagnosisRecordName'
		, (select a.ICDCODE from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=vnd.SUBSUFFIX and a.TYPEOFTHISDIAG = 1) as 'PrimaryDiagnosisCode'
		, (select dbo.ICDname(a.ICDCODE,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=vnd.SUBSUFFIX and a.TYPEOFTHISDIAG = 1) as 'PrimaryDiagnosisNameTH'
		, (select dbo.ICDname(a.ICDCODE,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=vnd.SUBSUFFIX and a.TYPEOFTHISDIAG = 1) as 'PrimaryDiagnosisNameEN'
		, vnd.PROCUDUREICDCMCODE1 as 'ICDCmCode1'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE1,2) as 'ICDCm1NameTH'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE1,1) as 'ICDCm1NameEN'
		, vnd.PROCUDUREICDCMCODE2 as 'ICDCmCode2'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE2,2) as 'ICDCm2NameTH'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE2,1) as 'ICDCm2NameEN'
		, vnd.PROCUDUREICDCMCODE3 as 'ICDCmCode3'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE3,2) as 'ICDCm3NameTH'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE3,1) as 'ICDCm3NameEN'
		, vnd.PROCUDUREICDCMCODE4 as 'ICDCmCode4'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE4,2) as 'ICDCm4NameTH'
		, dbo.ICDCMname(vnd.PROCUDUREICDCMCODE4,1) as 'ICDCm4NameEN'
		, (select a.PROCUDUREICDCMCODE1 from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCmCode5'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE1,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm5NameTH'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE1,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm5NameEN'
		, (select a.PROCUDUREICDCMCODE2 from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCmCode6'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE2,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm6NameTH'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE2,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm6NameEN'
		, (select a.PROCUDUREICDCMCODE3 from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCmCode7'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE3,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm7NameTH'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE3,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm7NameEN'
		, (select a.PROCUDUREICDCMCODE4 from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCmCode8'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE4,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm8NameTH'
		, (select dbo.ICDCMname(a.PROCUDUREICDCMCODE4,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2) as 'ICDCm8NameEN'
		, '' as 'ICDCmCode9'
		, '' as 'ICDCm9NameTH'
		, '' as 'ICDCm9NameEN'
		, '' as 'ICDCmCode10'
		, '' as 'ICDCm10NameTH'
		, '' as 'ICDCm10NameEN'
		, vnd.ENTRYBYUSERCODE as 'EntryByUserCode'
		, dbo.sysconname(vnd.ENTRYBYUSERCODE,10000,2) as 'EntryByUserNameTH'
		, dbo.sysconname(vnd.ENTRYBYUSERCODE,10000,1) as 'EntryByUserNameEN'
		, vnd.UPDATESTATDATETIME as 'RegisterDate'
		, '' as 'ChronicCreteriaCode'
		, '' as 'ChronicCreteriaName'
		, vnd.REMARKSMEMO as 'RemarksMemo'
		, vnd.ECODE as 'ECode'
		, dbo.ICDname(vnd.ECODE,2) as 'ECodeNameTH'
		, dbo.ICDname(vnd.ECODE,1) as 'ECodeNameEN'
		, (select a.ICDCODE from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2 and a.TYPEOFTHISDIAG = 4) as 'ComobidityCode1'
		, (select dbo.ICDname(a.ICDCODE,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2 and a.TYPEOFTHISDIAG = 4) as 'Comobidity1NameTH'
		, (select dbo.ICDname(a.ICDCODE,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=2 and a.TYPEOFTHISDIAG = 4) as 'Comobidity1NameEN'
		, (select a.ICDCODE from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=3 and a.TYPEOFTHISDIAG = 4) as 'ComobidityCode2'
		, (select dbo.ICDname(a.ICDCODE,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=3 and a.TYPEOFTHISDIAG = 4) as 'Comobidity2NameTH'
		, (select dbo.ICDname(a.ICDCODE,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=3 and a.TYPEOFTHISDIAG = 4) as 'Comobidity2NameEN'
		, (select a.ICDCODE from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=4 and a.TYPEOFTHISDIAG = 4) as 'ComobidityCode3'
		, (select dbo.ICDname(a.ICDCODE,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=4 and a.TYPEOFTHISDIAG = 4) as 'Comobidity3NameTH'
		, (select dbo.ICDname(a.ICDCODE,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=4 and a.TYPEOFTHISDIAG = 4) as 'Comobidity3NameEN'
		, (select a.ICDCODE from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=5 and a.TYPEOFTHISDIAG = 4) as 'ComobidityCode4'
		, (select dbo.ICDname(a.ICDCODE,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=5 and a.TYPEOFTHISDIAG = 4) as 'Comobidity4NameTH'
		, (select dbo.ICDname(a.ICDCODE,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=5 and a.TYPEOFTHISDIAG = 4) as 'Comobidity4NameEN'
		, (select a.ICDCODE from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=6 and a.TYPEOFTHISDIAG = 4) as 'ComobidityCode5'
		, (select dbo.ICDname(a.ICDCODE,2) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=6 and a.TYPEOFTHISDIAG = 4) as 'Comobidity5NameTH'
		, (select dbo.ICDname(a.ICDCODE,1) from VNDIAG a where a.VN=vnd.VN and a.VISITDATE=vnd.VISITDATE and a.SUFFIX=vnd.SUFFIX and a.SUBSUFFIX=6 and a.TYPEOFTHISDIAG = 4) as 'Comobidity5NameEN'
				from VNDIAG vnd
				inner join VNPRES vnp on vnd.VN=vnp.VN and vnd.VISITDATE=vnp.VISITDATE and vnd.SUFFIX=vnp.SUFFIX and vnd.SUBSUFFIX = 1
				inner join VNMST vnm on vnp.VN=vnm.VN and vnp.VISITDATE=vnm.VISITDATE