use SSBHOSPITAL
go

Select
		  'PTP' as 'BU'
		, CONCAT(format(med.VISITDATE,'yyyyMMdd'),med.VN,med.SUFFIX,format(med.MAKEDATETIME,'yyyyMMddHHmmssffff'),med.SUBSUFFIX) as 'OrderID'
		, vnm.HN as 'PatientID'
		, CONCAT(format(med.VISITDATE,'yyyyMMdd'),med.VN,med.SUFFIX) as 'VisitID'
		, med.VISITDATE as 'VisitDate'
		, med.VN as 'VN'
		, med.SUFFIX as 'PrescriptionNo'
		, vnp.CLINIC as 'ClinicCode' --modify 06/08/2569
		, dbo.sysconname(vnp.CLINIC,20016,2) as 'ClinicNameTH' --modify 06/08/2569
		, dbo.sysconname(vnp.CLINIC,20016,1) as 'ClinicNameEN' --modify 06/08/2569
		, vnp.DOCTOR as 'DoctorCode' --modify 06/08/2569
		, dbo.Doctorname(vnp.DOCTOR,4) as 'DoctorNameTH' --modify 06/08/2569
		, dbo.Doctorname(vnp.DOCTOR,4) as 'DoctorNameEN' --modify 06/08/2569
		, med.MAKEDATETIME as 'MakeDateTime'
		, med.STORE as 'StoreCode'
		, dbo.sysconname(med.STORE,40010,2) as 'StoreNameTH'
		, dbo.sysconname(med.STORE,40010,1) as 'StoreNameEN'
		, med.STOCKCODE as 'ItemCode'
		, dbo.CutSortChar(stm.THAINAME) as 'ItemNameTH'
		, dbo.CutSortChar(stm.ENGLISHNAME) as 'ItemNameEN'
		, Case When med.[REVERSE] = 1 Then med.QTY*(-1) Else med.QTY End as 'Qty'
		, med.UNITCODE as 'UnitCode'
		, dbo.sysconname(med.UNITCODE,40016,2) as 'UnitNameTH'
		, dbo.sysconname(med.UNITCODE,40016,1) as 'UnitNameEN'
		, med.UNITPRICE as 'UnitPrice'
		, med.AMT as 'ChargeAmt'
		,case when med.TYPEOFCHARGE = 0 then 'Charge'
							  when med.TYPEOFCHARGE = 1 then 'Free'
							  when med.TYPEOFCHARGE = 2 then 'Refund'
							  when med.TYPEOFCHARGE = 3 then 'Cxl'
							  when med.TYPEOFCHARGE = 4 then 'Usage FOC'
							  when med.TYPEOFCHARGE = 5 then 'Never Charge'
							  when med.TYPEOFCHARGE = 6 then 'Adjust'
							  when med.TYPEOFCHARGE = 7 then 'Return Usage FOC' end as 'ChargeType'
		, med.CHARGECODE as 'HNActivityCode'
		, dbo.sysconname(med.CHARGECODE,20023,2) as 'HNActivityNameTH'
		, dbo.sysconname(med.CHARGECODE,20023,1) as 'HNActivityNameEN'
		, med.RIGHTCODE as 'RightCode'
		, dbo.sysconname(med.RIGHTCODE,20019,2) as 'RightNameTH'
		, dbo.sysconname(med.RIGHTCODE,20019,1) as 'RightNameEN'
		, '' as 'DispendDrugReasonCode'
		, '' as 'DispendDrugReasonNameTH'
		, '' as 'DispendDrugReasonNameEN'
		, med.DOSETYPE as 'DoseTypeCode'
		, dbo.sysconname(med.DOSETYPE,20031,2) as 'DoseTypeNameTH'
		, dbo.sysconname(med.DOSETYPE,20031,1) as 'DoseTypeNameEN'
		, med.DOSECODE as 'DoseCode'
		, dbo.sysconname(med.DOSECODE,20032,2) as 'DoseNameTH'
		, dbo.sysconname(med.DOSECODE,20032,1) as 'DoseNameEN'
		, CAST(SUBSTRING(sys01.COM,1,1)as Int) as 'NumberDosePerDay'
		, '' as 'BeforeAfterMealType'
		, '' as 'BeforeAfterMealTypeName'
		, med.DOSEQTYCODE as 'DoseQtyCode'
		, dbo.sysconname(med.DOSEQTYCODE,20033,2) as 'DoseQtyNameTH'
		, dbo.sysconname(med.DOSEQTYCODE,20033,1) as 'DoseQtyNameEN'
		, '' as 'StatDoseQtyCode'
		, '' as 'StatDoseQtyNameTH'
		, '' as 'StatDoseQtyNameEN'
		, med.DOSEUNITCODE as 'DoseUnitCode'
		, dbo.sysconname(med.DOSEUNITCODE,20034,2) as 'DoseUnitNameTH'
		, dbo.sysconname(med.DOSEUNITCODE,20034,1) as 'DoseUnitNameEN'
		, med.NODAYDOSE as 'NumberDayDose'
		, '' as 'DoseFreqCode'
		, '' as 'DoseFreqNameTH'
		, '' as 'DoseFreqNameEN'
		, med.AUXLABEL1 as 'AuxLabel1Code'
		, dbo.sysconname(med.AUXLABEL1,20030,2) as 'AuxLabel1NameTH'
		, dbo.sysconname(med.AUXLABEL1,20030,1) as 'AuxLabel1NameEN'
		, med.AUXLABEL2 as 'AuxLabel2Code'
		, dbo.sysconname(med.AUXLABEL2,20030,2) as 'AuxLabel2NameTH'
		, dbo.sysconname(med.AUXLABEL2,20030,1) as 'AuxLabel2NameEN'
		, med.AUXLABEL3 as 'AuxLabel3Code'
		, dbo.sysconname(med.AUXLABEL3,20030,2) as 'AuxLabel3NameTH'
		, dbo.sysconname(med.AUXLABEL3,20030,1) as 'AuxLabel3NameEN'
		, med.DOSEMEMO as 'DoseMemo'
		, med.RETURNDRUGREASON as 'ReturnOpdDrugReasonCode'
		, dbo.sysconname(med.RETURNDRUGREASON,20639,2) as 'ReturnOpdDrugReasonnameTH'
		, dbo.sysconname(med.RETURNDRUGREASON,20639,1) as 'ReturnOpdDrugReasonNameEN'
		, '' as 'DoctorApproved'
		, '' as 'DrugRepeatType'
		, '' as 'DrugRepeatTypeName'
		, '' as 'HNDrugErrorCodeTypeCode'
		, '' as 'HNDrugErrorCodeTypeName'
		, '' as 'HNAllergicErrorCodeTypeCode'
		, '' as 'HNAllergicErrorCodeTypeName'
		, stm.NETPRICE as 'NetPrice'
		, '' as 'OutsideHospitalDrug'
		, '' as 'StartDoseDateTime'
		, '' as 'FinishDoseDateTime'
				From VNMEDICINE med
				Inner Join VNPRES vnp on med.VN=vnp.VN and med.VISITDATE=vnp.VISITDATE and med.SUFFIX=vnp.SUFFIX
				Inner Join VNMST vnm on vnp.VN=vnm.VN and vnp.VISITDATE=vnm.VISITDATE
				inner Join SSBSTOCK.dbo.STOCK_MASTER stm on med.STOCKCODE=stm.STOCKCODE and stm.MAINCATEGORY = 'ME'
				Left Join SYSCONFIG sys01 on med.DOSECODE=sys01.CODE and sys01.CTRLCODE = 20032
				Where	1=1 
				--and med.VISITDATE = '2026-04-02'
