select 'PLR' as "BU"
, v.patient_id as "PatientID"
, v.visit_id as "VisitID"
, v.visit_date as "VisitDate"
, format_vn(v.vn) as "VN"
, ROW_NUMBER() OVER (PARTITION BY v.visit_id ORDER BY (v.visit_id, ap.attending_physician_id) ) as "PrescriptionNo"
, '' as "Suffix"
--���
, bd.base_department_id as "ClinicCode"
, bd.description as "ClinicNameTH"
, '' as "ClinicNameEN"
--
, di.diagnosis_date ||' '|| di.diagnosis_time as "DiagDateTime"
--��
, di.icd10_code as "PrimaryDiagnosisCode"
, di.icd10_description as "PrimaryDiagnosisNameTH"
, '' as "PrimaryDiagnosisNameEN"
--
--����
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',1) as "ICDCmCode1"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',1) as "ICDCm1NameTH"
, '' as "ICDCm1NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',2) as "ICDCmCode2"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',2) as "ICDCm2NameTH"
, '' as "ICDCm2NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',3) as "ICDCmCode3"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',3) as "ICDCm3NameTH"
, '' as "ICDCm3NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',4) as "ICDCmCode4"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',4) as "ICDCm4NameTH"
, '' as "ICDCm4NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',5) as "ICDCmCode5"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',5) as "ICDCm5NameTH"
, '' as "ICDCm5NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',6) as "ICDCmCode6"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',6) as "ICDCm6NameTH"
, '' as "ICDCm6NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',7) as "ICDCmCode7"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',7) as "ICDCm7NameTH"
, '' as "ICDCm7NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',8) as "ICDCmCode8"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',8) as "ICDCm8NameTH"
, '' as "ICDCm8NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',9) as "ICDCmCode9"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',9) as "ICDCm9NameTH"
, '' as "ICDCm9NameEN"
, split_part(his_func_get_icd9(v.visit_id, '1'),'|',10) as "ICDCmCode10"
, split_part(his_func_get_icd9(v.visit_id, '2'),'|',10) as "ICDCm10NameTH"
, '' as "ICDCm10NameEN"
--
, di.modify_eid as "EntryByUserCode"
, e2.prename || e2.firstname || ' ' || e2.lastname as "EntryByUserNameTH"
, e2.intername as "EntryByUserNameEN"
, di.modify_date as "RegisterDate"
, '' as "ChronicCreteriaCode"
, '' as "ChronicCreteriaName"
, '' as "RemarksMemo"
, split_part(his_func_get_diagnosis(v.visit_id, '5', '1'),'|',1) as "ECode"
, split_part(his_func_get_diagnosis(v.visit_id, '5', '2'),'|',1) as "ECodeNameTH"
, '' as "ECodeNameEN"
--����
, split_part(his_func_get_diagnosis(v.visit_id, '2', '1'),'|',1) as "ComobidityCode1"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '2'),'|',1) as "Comobidity1NameTH"
, '' as "Comobidity1NameEN"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '1'),'|',2) as "ComobidityCode2"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '2'),'|',2) as "Comobidity2NameTH"
, '' as "Comobidity2NameEN"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '1'),'|',3) as "ComobidityCode3"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '2'),'|',3) as "Comobidity3NameTH"
, '' as "Comobidity3NameEN"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '1'),'|',4) as "ComobidityCode4"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '2'),'|',4) as "Comobidity4NameTH"
, '' as "Comobidity4NameEN"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '1'),'|',5) as "ComobidityCode5"
, split_part(his_func_get_diagnosis(v.visit_id, '2', '2'),'|',5) as "Comobidity5NameTH"
, '' as "Comobidity5NameEN"
--
from visit v 
left join attending_physician ap on v.visit_id = ap.visit_id 
left join base_department bd on ap.base_department_id = bd.base_department_id and bd.account_product  = 'COST'
left join diagnosis_icd10 di on v.visit_id = di.visit_id and di.fix_diagnosis_type_id = '1' and ap.employee_id = di.doctor_eid 
left join employee e2 on e2.employee_code = di.doctor_eid 
left join patient p on p.patient_id = v.patient_id
where v.visit_date = current_date::text
--    limit 100