use SSBLIVE
go

select	--top 50
		'PT2' as 'BU'
		,lh.HN as 'PatientID'
		,lh.FacilityRmsNo as 'FacilityRmsNo'
		,lh.RequestNo as 'RequestNo'
		,lh.EntryDateTime as 'EntryDateTime'
		,lh.RequestDoctor as 'RequestDoctorCode'
		,dbo.Doctorname(lh.RequestDoctor,2) as 'RequestDoctorNameTH'
		,dbo.Doctorname(lh.RequestDoctor,1) as 'RequestDoctorNameEN'
		,ls.LabCodeSuffixTiny as 'LabCodeSuffixTiny'
		,ls.SuffixTiny as 'SuffixTiny'
		,ls.SpecimenCode as 'SpecimenCode'
		,dbo.sysconname(ls.SpecimenCode,42121,2) as 'SpecimenNameTH'
		,dbo.sysconname(ls.SpecimenCode,42121,1) as 'SpecimenNameEN'
		,ls.RequestLabCode as 'RequestLabCode'
		,dbo.sysconname(ls.RequestLabCode,42136,2) as 'RequestLabNameTH'
		,dbo.sysconname(ls.RequestLabCode,42136,1) as 'RequestLabNameEN'
		,ls.LabCode as 'LabCode'
		,dbo.sysconname(ls.LabCode,42136,2) as 'LabNameTH'
		,dbo.sysconname(ls.LabCode,42136,1) as 'LabNameEN'
		,ls.ResultValue as 'ResultValue'
		,ls.FacilityResultType as 'FacilityResultType'	
		,case 
			when ls.FacilityResultType = '0' then 'None'
			when ls.FacilityResultType = '1' then 'Abnormal'
			when ls.FacilityResultType = '2' then 'Hiden'
			when ls.FacilityResultType = '3' then 'Found'
		end as 'FacilityResultName'
		,ls.LABResultClassifiedType as 'LABResultClassifiedType'
		,case
			when ls.LABResultClassifiedType = '0' then 'None'
			when ls.LABResultClassifiedType = '1' then 'Low'
			when ls.LABResultClassifiedType = '2' then 'Normal'
			when ls.LABResultClassifiedType = '3' then 'High'
			when ls.LABResultClassifiedType = '8' then 'Negative'
			when ls.LABResultClassifiedType = '9' then 'Positive'
			when ls.LABResultClassifiedType = '10' then 'Abnormal'
		end as 'LABResultClassifiedName'
		,ls.NormalResultValue as 'NormalResultValue'
		,ls.ResultDateTime as 'ResultDateTime'
		,ls.ConfirmByUserCode as 'ConfirmByUserCode'
		,dbo.sysconname(ls.ConfirmByUserCode,10031,2) as 'ConfirmByUserNameTH'
		,dbo.sysconname(ls.ConfirmByUserCode,10031,1) as 'ConfirmByUserNameEN'
		,ls.ConfirmDateTime as 'ConfirmDateTime'
		,ls.ApproveByUserCode as 'ApproveByUserCode'
		,dbo.sysconname(ls.ApproveByUserCode,10031,2) as 'ApproveByUserNameTH'
		,dbo.sysconname(ls.ApproveByUserCode,10031,1) as 'ApproveByUserNameEN'
		,ls.ApproveDateTime as 'ApproveDateTime'
		,ls.PreviousResultValue as 'PreviousResultValue'
		,ls.PreviousResultDateTime as 'PreviousResultDateTime'
		,lh.CxlRequestByUserCode as 'CancelByUserCode'
		,dbo.sysconname(lh.CxlRequestByUserCode,10031,2) as 'CancelByUserNameTH'
		,dbo.sysconname(lh.CxlRequestByUserCode,10031,1) as 'CancelByUserNameEN'
		,lh.CxlDateTime as 'CancelDateTime'
		, case when lh.CheckUp = 1 then lh.RequestFromRequestNo else null end as 'CheckupNo'
		, case when lh.Ward is not null then lh.Ward else lh.Clinic end as FromLocationCode
		, case when lh.Ward is not null then dbo.sysconname(lh.Ward,42201,2) else dbo.sysconname(lh.Clinic,42203,2) end as FromLocationNameTH
		, case when lh.Ward is not null then dbo.sysconname(lh.Ward,42201,1) else dbo.sysconname(lh.Clinic,42203,1) end as FromLocationNameEN
from	HNLABREQ_HEADER lh
		left join HNLABREQ_RESULT ls on lh.RequestNo=ls.RequestNo and lh.FacilityRmsNo=ls.FacilityRmsNo
--where	lh.EntryDateTime between '2025-11-01 00:00:00' and '2025-11-03 23:59:59'
--		and ls.RequestLabCode = 'MIC002000';