select top 10
		 'PT2' as 'BU'
		, xh.HN as 'PatientID'
		, xh.FacilityRmsNo as 'FacilityRmsNo'
		, xh.RequestNo as 'RequestNo'
		, xh.EntryDateTime as 'EntryDateTime'
		, xh.RequestDoctor as 'RequestDoctorCode'
		, dbo.Doctorname(xh.RequestDoctor,2) as 'RequestDoctorNameTH'
		, dbo.Doctorname(xh.RequestDoctor,1) as 'RequestDoctorNameEN'
		, xh.AcknowledgeDateTime as 'AcknowledgeDateTime'
		, xs.ResultSuffixSmall as 'ResultSuffixSmall'
		, xs.XrayCodeCollection as 'XrayCode'
		, dbo.sysconname(xs.XrayCodeCollection,42179,2) as 'XrayNameTH'
		, dbo.sysconname(xs.XrayCodeCollection,42179,1) as 'XrayNameEN'
		, xs.ConfirmResultDateTime as 'ConfirmResultDateTime'
		, xs.ResultDoctor as 'ResultDoctorCode'
		, dbo.Doctorname(xs.ResultDoctor,2) as 'ResultDoctorNameTH'
		, dbo.Doctorname(xs.ResultDoctor,1) as 'ResultDoctorNameEN'
		, xs.ResultMemo as 'ResultMemo'
		, xs.CxlByUserCode as 'CancelByUserCode'
		, dbo.sysconname(xs.CxlByUserCode,10031,2) as 'CancelByUserNameTH'
		, dbo.sysconname(xs.CxlByUserCode,10031,1) as 'CancelByUserNameEN'
		, xs.CxlDateTime as 'CancelDateTime'
				from HNXRAYREQ_HEADER xh
				left join HNXRAYREQ_RESULT xs on xh.FacilityRmsNo=xs.FacilityRmsNo and xh.RequestNo=xs.RequestNo