select top 10 
	'PLS' as 'BU'
	, a.HN as 'PatientID'
	, a.HN
	, a.VISITOUTDATETIME as 'ReferDateTime' 
	, a.VISITDATE as 'VisitDate'
	, a.VN as 'VN'
	, '' as 'AN'
	, '' as 'AdmitDateTime'
	, b.DOCTOR as 'DoctorCode'
	, dbo.Doctorname(b.DOCTOR,2) as 'DoctorNameTH'
	, dbo.Doctorname(b.DOCTOR,1) as 'DoctorNameEN'
	,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
	,doc.CLINIC as 'DoctorClinicCode'
	,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
	,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
	, '' as 'DoctorDepartmentCode'
	, '' as 'DoctorDepartmentNameTH'
	, '' as 'DoctorDepartmentNameEN'
	,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
	,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
	,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
	, 'ReferOut' as 'Refer'
	, '' as 'ReferFromType'
	, '' as 'ReferFromNameTH'
	, '' as 'ReferFromNameEN'
	, REFERTOTYPE as 'ReferToType'
	, dbo.sysconname(REFERTOTYPE,20060,2) as 'ReferToNameTH'
	, dbo.sysconname(REFERTOTYPE,20060,1) as 'ReferToNameEN'
	, '' as 'ReferFromHospital'
	, '' as 'ReferFromHospitalNameTH'
	, '' as 'ReferFromHospitalNameEN'
	, REFERTOHOSPITAL as 'ReferToHospital'
	, dbo.sysconname(REFERTOHOSPITAL,20010,2) as 'ReferToHospitalNameTH'
	, dbo.sysconname(REFERTOHOSPITAL,20010,1) as 'ReferToHospitalNameEN'
	, a.REFERTOREMARKS as 'Remarks'
	, c.ICDCODE as 'Diag'
	, d.THAINAME as 'DiagNameTH'
	, d.ENGLISHNAME as 'DiagNameEN'
		from VNMST a
		inner join VNPRES b on a.VN=b.VN and a.VISITDATE=b.VISITDATE and REFERTOTYPE is not null
		left join VNDIAG c on b.VN=c.VN and b.VISITDATE=c.VISITDATE and b.SUFFIX=c.SUFFIX and c.TYPEOFTHISDIAG = 1
		left join ICD_MASTER d on c.ICDCODE=d.ICDCODE
		left join HNDOCTOR doc on b.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
Union ALL
select top 10 
	'PLS' as 'BU'
	, a.HN as 'PatientID'
	, a.HN
	, a.VISITINDATETIME as 'ReferDateTime' 
	, a.VISITDATE as 'VisitDate'
	, a.VN as 'VN'
	, '' as 'AN'
	, '' as 'AdmitDateTime'
	, b.DOCTOR as 'DoctorCode'
	, dbo.Doctorname(b.DOCTOR,2) as 'DoctorNameTH'
	, dbo.Doctorname(b.DOCTOR,1) as 'DoctorNameEN'
	,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
	,doc.CLINIC as 'DoctorClinicCode'
	,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
	,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
	, '' as 'DoctorDepartmentCode'
	, '' as 'DoctorDepartmentNameTH'
	, '' as 'DoctorDepartmentNameEN'
	,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
	,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
	,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
	, 'ReferIn' as 'Refer'
	, REFERFROMTYPE as 'ReferFromType'
	, dbo.sysconname(REFERFROMTYPE,20059,2) as 'ReferFromNameTH'
	, dbo.sysconname(REFERFROMTYPE,20059,1) as 'ReferFromNameEN'
	, '' as 'ReferToType'
	, '' as 'ReferToNameTH'
	, '' as 'ReferToNameEN'
	, REFERFROMHOSPITAL as 'ReferFromHospital'
	, dbo.sysconname(REFERFROMHOSPITAL,20010,2) as 'ReferFromHospitalNameTH'
	, dbo.sysconname(REFERFROMHOSPITAL,20010,1) as 'ReferFromHospitalNameEN'
	, '' as 'ReferToHospital'
	, '' as 'ReferToHospitalNameTH'
	, '' as 'ReferToHospitalNameEN'
	, a.REFERFROMREMARKS as 'Remarks'
	, c.ICDCODE as 'Diag'
	, d.THAINAME as 'DiagNameTH'
	, d.ENGLISHNAME as 'DiagNameEN'
		from VNMST a
		inner join VNPRES b on a.VN=b.VN and a.VISITDATE=b.VISITDATE and REFERFROMTYPE is not null
		left join VNDIAG c on b.VN=c.VN and b.VISITDATE=c.VISITDATE and b.SUFFIX=c.SUFFIX and c.TYPEOFTHISDIAG = 1
		left join ICD_MASTER d on c.ICDCODE=d.ICDCODE
		left join HNDOCTOR doc on b.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
Union ALL
select top 10 
	'PLS' as 'BU'
	, a.HN as 'PatientID'
	, a.HN
	, a.DISCHARGEDATETIME as 'ReferDateTime'
	, '' as 'VisitDate'
	, '' as 'VN'
	, a.AN as 'AN'
	, a.ADMDATETIME as 'AdmitDateTime'
	, b.DOCTOR as 'DoctorCode'
	, dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
	, dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
	,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
	,doc.CLINIC as 'DoctorClinicCode'
	,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
	,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
	, '' as 'DoctorDepartmentCode'
	, '' as 'DoctorDepartmentNameTH'
	, '' as 'DoctorDepartmentNameEN'
	,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
	,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
	,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
	, 'ReferOut' as 'Refer'
	, '' as 'ReferFromType'
	, '' as 'ReferFromNameTH'
	, '' as 'ReferFromNameEN'
	, REFERTOTYPE as 'ReferToType'
	, dbo.sysconname(REFERTOTYPE,20060,2) as 'ReferToNameTH'
	, dbo.sysconname(REFERTOTYPE,20060,1) as 'ReferToNameEN'
	, '' as 'ReferFromHospital'
	, '' as 'ReferFromHospitalNameTH'
	, '' as 'ReferFromHospitalNameEN'
	, REFERTOHOSPITAL as 'ReferToHospital'
	, dbo.sysconname(REFERTOHOSPITAL,20010,2) as 'ReferToHospitalNameTH'
	, dbo.sysconname(REFERTOHOSPITAL,20010,1) as 'ReferToHospitalNameEN'
	, a.REFERTOREMARKS as 'Remarks'
	, c.DIAGNOSES as 'Diag'
	, d.THAINAME as 'DiagNameTH'
	, d.ENGLISHNAME as 'DiagNameEN'
		from ADMMASTER a
		inner join IPDDOCTOR b on a.AN=b.AN and b.SPECIALIZEDOCTORTYPE = 1 and a.REFERTOTYPE is not null
		inner join HNDOCTOR doc on b.DOCTOR=doc.DOCTOR
		left join IPDSUMMARY c on a.AN=c.AN and c.SUFFIX = 1
		left join ICD_MASTER d on c.DIAGNOSES=d.ICDCODE
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
Union ALL
select top 10 
	'PLS' as 'BU'
	, a.HN as 'PatientID'
	, a.HN
	, a.ADMDATETIME as 'ReferDateTime'
	, '' as 'VisitDate'
	, '' as 'VN'
	, a.AN as 'AN'
	, a.ADMDATETIME as 'AdmitDateTime'
	, b.DOCTOR as 'DoctorCode'
	, dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
	, dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
	,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
	,doc.CLINIC as 'DoctorClinicCode'
	,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
	,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
	, '' as 'DoctorDepartmentCode'
	, '' as 'DoctorDepartmentNameTH'
	, '' as 'DoctorDepartmentNameEN'
	,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
	,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
	,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
	, 'ReferIn' as 'Refer'
	, REFERFROMTYPE as 'ReferFromType'
	, dbo.sysconname(REFERFROMTYPE,20059,2) as 'ReferFromNameTH'
	, dbo.sysconname(REFERFROMTYPE,20059,1) as 'ReferFromNameEN'
	, '' as 'ReferToType'
	, '' as 'ReferToNameTH'
	, '' as 'ReferToNameEN'
	, REFERFROMHOSPITAL as 'ReferFromHospital'
	, dbo.sysconname(REFERFROMHOSPITAL,20010,2) as 'ReferFromHospitalNameTH'
	, dbo.sysconname(REFERFROMHOSPITAL,20010,1) as 'ReferFromHospitalNameEN'
	, '' as 'ReferToHospital'
	, '' as 'ReferToHospitalNameTH'
	, '' as 'ReferToHospitalNameEN'
	, a.REFERFROMHOSPITAL as 'Remarks'
	, c.DIAGNOSES as 'Diag'
	, d.THAINAME as 'DiagNameTH'
	, d.ENGLISHNAME as 'DiagNameEN'
		from ADMMASTER a
		inner join IPDDOCTOR b on a.AN=b.AN and b.SPECIALIZEDOCTORTYPE = 1 and a.REFERFROMTYPE is not null
		inner join HNDOCTOR doc on b.DOCTOR=doc.DOCTOR
		left join IPDSUMMARY c on a.AN=c.AN and c.SUFFIX = 1
		left join ICD_MASTER d on c.DIAGNOSES=d.ICDCODE
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015