select top 100
'PLS' as 'BU'
,vnm.HN as 'PatientID'
,convert(varchar,vnp.VISITDATE,112)+convert(varchar,vnp.VN)+convert(varchar,vnp.SUFFIX) as 'VisitID'
,vnp.VISITDATE as 'VisitDate'
,vnp.VN as 'VN'
,vnp.SUFFIX as 'PrescriptionNo'
,vnp.CLINIC as 'ClinicCode'
,dbo.sysconname(vnp.CLINIC,20016,2) as 'ClinicNameTH' 
,dbo.sysconname(vnp.CLINIC,20016,1) as 'ClinicNameEN' 
,'' as 'ClinicDepartmentCode'
,'' as 'ClinicDepartmentNameTH'
,'' as 'ClinicDepartmentNameEN'
,vnp.DOCTOR as 'DoctorCode'
,dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
,dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
,doc.CLINIC as 'DoctorClinicCode'
,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
, '' as 'DoctorDepartmentCode'
, '' as 'DoctorDepartmentNameTH'
, '' as 'DoctorDepartmentNameEN'
,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
,vnp.CLOSEVISITTYPE as 'CloseVisitCode'
,dbo.sysconname(vnp.CLOSEVISITTYPE,20043,2) as 'CloseVisitNameTH' 
,dbo.sysconname(vnp.CLOSEVISITTYPE,20043,1) as 'CloseVisitNameEN' 
,vnp.APPOINTMENTNO as 'AppointmentNo'
,case when CLOSEVISITTYPE is null then 'Active' else 'InActive' end as 'Status'
,vnp.REGINDATETIME as 'RegInDateTime' 
,vnp.DISGRMS as 'DiagRms' 
,dbo.sysconname(vnp.DISGRMS,20042,4) as 'DiagRmsName' 
,vnm.NEWPATIENT as 'NEWPATIENT' 
,vnm.VISITOUTDATETIME as 'CloseVisitDateTime' 
,vnm.VISITINDATETIME as 'MakeDateTime' 
,vnm.USEDRIGHTCODE as 'DefaultRightCode' 
,dbo.sysconname(vnm.USEDRIGHTCODE,20019,2) as 'DefaultRightNameTH' 
,dbo.sysconname(vnm.USEDRIGHTCODE,20019,1) as 'DefaultRightNameEN' 
,vnm.ACCIDENT as 'AccidentCode' 
,'' as 'AccidentNameTH' 
,'' as 'AccidentNameEN' 
,'' as 'ComposeDept'
,'' as 'VisitCode'
,'' as 'VisitNameTH'
,'' as 'VisitNameEN'
,vnp.ISSUEBYUSERID as 'EntryByUserCode'
,dbo.sysconname(vnp.ISSUEBYUSERID,10000,2) as 'EntryByUserNameTH'
,dbo.sysconname(vnp.ISSUEBYUSERID,10000,1) as 'EntryByUserNameEN'
,'' as 'ReVisitCode'
,'' as 'ReVisitNameTH'
,'' as 'ReVisitNameEN'
		from VNPRES vnp
		left join VNMST vnm on vnp.VN=vnm.VN and vnp.VISITDATE=vnm.VISITDATE
		left join HNDOCTOR doc on vnp.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
		where vnp.DISGRMS = '111' --BU = PLS
union all
select top 100
'PTP' as 'BU'
,vnm.HN as 'PatientID'
,convert(varchar,vnp.VISITDATE,112)+convert(varchar,vnp.VN)+convert(varchar,vnp.SUFFIX) as 'VisitID'
,vnp.VISITDATE as 'VisitDate'
,vnp.VN as 'VN'
,vnp.SUFFIX as 'PrescriptionNo'
,vnp.CLINIC as 'ClinicCode'
,dbo.sysconname(vnp.CLINIC,20016,2) as 'ClinicNameTH' 
,dbo.sysconname(vnp.CLINIC,20016,1) as 'ClinicNameEN' 
,'' as 'ClinicDepartmentCode'
,'' as 'ClinicDepartmentNameTH'
,'' as 'ClinicDepartmentNameEN'
,vnp.DOCTOR as 'DoctorCode'
,dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
,dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
,doc.CLINIC as 'DoctorClinicCode'
,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
, '' as 'DoctorDepartmentCode'
, '' as 'DoctorDepartmentNameTH'
, '' as 'DoctorDepartmentNameEN'
,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
,vnp.CLOSEVISITTYPE as 'CloseVisitCode'
,dbo.sysconname(vnp.CLOSEVISITTYPE,20043,2) as 'CloseVisitNameTH' 
,dbo.sysconname(vnp.CLOSEVISITTYPE,20043,1) as 'CloseVisitNameEN' 
,vnp.APPOINTMENTNO as 'AppointmentNo'
,case when CLOSEVISITTYPE is null then 'Active' else 'InActive' end as 'Status'
,vnp.REGINDATETIME as 'RegInDateTime' 
,vnp.DISGRMS as 'DiagRms' 
,dbo.sysconname(vnp.DISGRMS,20042,4) as 'DiagRmsName' 
,vnm.NEWPATIENT as 'NEWPATIENT' 
,vnm.VISITOUTDATETIME as 'CloseVisitDateTime' 
,vnm.VISITINDATETIME as 'MakeDateTime' 
,vnm.USEDRIGHTCODE as 'DefaultRightCode' 
,dbo.sysconname(vnm.USEDRIGHTCODE,20019,2) as 'DefaultRightNameTH' 
,dbo.sysconname(vnm.USEDRIGHTCODE,20019,1) as 'DefaultRightNameEN' 
,vnm.ACCIDENT as 'AccidentCode' 
,'' as 'AccidentNameTH' 
,'' as 'AccidentNameEN' 
,'' as 'ComposeDept'
,'' as 'VisitCode'
,'' as 'VisitNameTH'
,'' as 'VisitNameEN'
,vnp.ISSUEBYUSERID as 'EntryByUserCode'
,dbo.sysconname(vnp.ISSUEBYUSERID,10000,2) as 'EntryByUserNameTH'
,dbo.sysconname(vnp.ISSUEBYUSERID,10000,1) as 'EntryByUserNameEN'
,'' as 'ReVisitCode'
,'' as 'ReVisitNameTH'
,'' as 'ReVisitNameEN'
		from VNPRES vnp
		left join VNMST vnm on vnp.VN=vnm.VN and vnp.VISITDATE=vnm.VISITDATE
		left join HNDOCTOR doc on vnp.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
		where vnp.DISGRMS = 'T' --BU = PTP
union all
select top 100
'PTN' as 'BU'
,vnm.HN as 'PatientID'
,convert(varchar,vnp.VISITDATE,112)+convert(varchar,vnp.VN)+convert(varchar,vnp.SUFFIX) as 'VisitID'
,vnp.VISITDATE as 'VisitDate'
,vnp.VN as 'VN'
,vnp.SUFFIX as 'PrescriptionNo'
,vnp.CLINIC as 'ClinicCode'
,dbo.sysconname(vnp.CLINIC,20016,2) as 'ClinicNameTH' 
,dbo.sysconname(vnp.CLINIC,20016,1) as 'ClinicNameEN' 
,'' as 'ClinicDepartmentCode'
,'' as 'ClinicDepartmentNameTH'
,'' as 'ClinicDepartmentNameEN'
,vnp.DOCTOR as 'DoctorCode'
,dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
,dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
,doc.CERTIFYPUBLICNO as 'DoctorCertificate'
,doc.CLINIC as 'DoctorClinicCode'
,dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
,dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
, '' as 'DoctorDepartmentCode'
, '' as 'DoctorDepartmentNameTH'
, '' as 'DoctorDepartmentNameEN'
,doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
,dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
,dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
,vnp.CLOSEVISITTYPE as 'CloseVisitCode'
,dbo.sysconname(vnp.CLOSEVISITTYPE,20043,2) as 'CloseVisitNameTH' 
,dbo.sysconname(vnp.CLOSEVISITTYPE,20043,1) as 'CloseVisitNameEN' 
,vnp.APPOINTMENTNO as 'AppointmentNo'
,case when CLOSEVISITTYPE is null then 'Active' else 'InActive' end as 'Status'
,vnp.REGINDATETIME as 'RegInDateTime' 
,vnp.DISGRMS as 'DiagRms' 
,dbo.sysconname(vnp.DISGRMS,20042,4) as 'DiagRmsName' 
,vnm.NEWPATIENT as 'NEWPATIENT' 
,vnm.VISITOUTDATETIME as 'CloseVisitDateTime' 
,vnm.VISITINDATETIME as 'MakeDateTime' 
,vnm.USEDRIGHTCODE as 'DefaultRightCode' 
,dbo.sysconname(vnm.USEDRIGHTCODE,20019,2) as 'DefaultRightNameTH' 
,dbo.sysconname(vnm.USEDRIGHTCODE,20019,1) as 'DefaultRightNameEN' 
,vnm.ACCIDENT as 'AccidentCode' 
,'' as 'AccidentNameTH' 
,'' as 'AccidentNameEN' 
,'' as 'ComposeDept'
,'' as 'VisitCode'
,'' as 'VisitNameTH'
,'' as 'VisitNameEN'
,vnp.ISSUEBYUSERID as 'EntryByUserCode'
,dbo.sysconname(vnp.ISSUEBYUSERID,10000,2) as 'EntryByUserNameTH'
,dbo.sysconname(vnp.ISSUEBYUSERID,10000,1) as 'EntryByUserNameEN'
,'' as 'ReVisitCode'
,'' as 'ReVisitNameTH'
,'' as 'ReVisitNameEN'
		from VNPRES vnp
		left join VNMST vnm on vnp.VN=vnm.VN and vnp.VISITDATE=vnm.VISITDATE
		left join HNDOCTOR doc on vnp.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
		where vnp.DISGRMS = 'TM' --BU = PTN