select
		  'PLS' as BU
		, '' as LabCode
		, '' as LabCodeNameTH
		, '' as LabCodeNameEN
		, '' as Gender
		, '' as GenderNameTH
		, '' as GenderNameEN
		, '' as AgeYearFrom
		, '' as AgeMonthFrom
		, '' as AgeDayFrom
		, '' as AgeYearTo
		, '' as AgeMonthTo
		, '' as AgeDayTo
		, '' as NormalValueFrom
		, '' as NormalValueTo
		, '' as OrNormalValueFrom
		, '' as OrNormalValueTo
		, '' as LabCommentCode
		, '' as LabCommentNameTH
		, '' as LabCommentNameEN
		, '' as LabCommentSelection1
		, '' as LabCommentSelection1NameTH
		, '' as LabCommentSelection1NameEN
		, '' as LabCommentSelection2
		, '' as LabCommentSelection2NameTH
		, '' as LabCommentSelection2NameEN
		, '' as LabCommentSelection3
		, '' as LabCommentSelection3NameTH
		, '' as LabCommentSelection3NameEN
		, '' as LabCommentSelection4
		, '' as LabCommentSelection4NameTH
		, '' as LabCommentSelection4NameEN
		, '' as ConclusionResultTH
		, '' as ConclusionResultEN
		, '' as LabCommentAddition1
		, '' as LabCommentAddition1NameTH
		, '' as LabCommentAddition1NameEN
		, '' as LabCommentAddition2
		, '' as LabCommentAddition2NameTH
		, '' as LabCommentAddition2NameEN
		, '' as LabCommentAddition3
		, '' as LabCommentAddition3NameTH
		, '' as LabCommentAddition3NameEN
		, '' as LabCommentAddition4
		, '' as LabCommentAddition4NameTH
		, '' as LabCommentAddition4NameEN
		, '' as Doctor1
		, '' as Doctor1NameTH
		, '' as Doctor1NameEN
		, '' as Doctor2
		, '' as Doctor2NameTH
		, '' as Doctor2NameEN
		, '' as Doctor3
		, '' as Doctor3NameTH
		, '' as Doctor3NameEN
		, '' as Doctor4
		, '' as Doctor4NameTH
		, '' as Doctor4NameEN
		, '' as Doctor5
		, '' as Doctor5NameTH
		, '' as Doctor5NameEN
		, '' as Doctor6
		, '' as Doctor6NameTH
		, '' as Doctor6NameEN
