select  'PLS' as 'BU'
,'' as 'PatientID'
,'' as 'FacilityRmsNo'
,'' as 'RequestNo'
,'' as 'VisitDateTime'
,'' as 'HNORVisitLocation'
,'' as 'HNORVisitType'
,'' as 'ORAnesType'
,'' as 'NurseCode'
,'' as 'NurseNameTH'
,'' as 'NurseNameEN'
,'' as 'Doctor'
,'' as 'RequestDoctorNameTH'
,'' as 'RequestDoctorNameEN'