select 
 'PLS' as 'BU'
,orr.HN as 'PatientID'
,orr.FACILITYRMSNO as 'FacilityRmsNo'
,orr.REQUESTNO as 'RequestNo'
,orr.ENTRYDATETIME as 'EntryDateTime'
,orch.IPDCHARGEMAKEDATETIME as 'ChargeDateTime'
,orch.SUFFIX as 'SuffixSmall'
,orch.SUFFIX as 'ChargeSuffix'
,orch.TREATMENTCODE as 'ItemCode'
,dbo.sysconname(orch.TREATMENTCODE,20051,2) as 'ItemNameTH'
,dbo.sysconname(orch.TREATMENTCODE,20051,1) as 'ItemNameEN'
,orch.CHARGECODE as 'ActivityCode'
,dbo.sysconname(orch.CHARGECODE,20023,2) as 'ActivityNameTH'
,dbo.sysconname(orch.CHARGECODE,20023,1) as 'ActivityNameEN'
,case when orch.TYPEOFCHARGE = 0 then 'None'
	  when orch.TYPEOFCHARGE = 1 then 'Free'
	  when orch.TYPEOFCHARGE = 2 then 'Refund'
	  when orch.TYPEOFCHARGE = 3 then 'Cxl'
	  when orch.TYPEOFCHARGE = 4 then 'Usage_FOC'
	  when orch.TYPEOFCHARGE = 5 then 'Never_Charge'
	  when orch.TYPEOFCHARGE = 6 then 'Adjust'
	  when orch.TYPEOFCHARGE = 7 then 'Return_Usage_FOC'
 end as 'ChargeType'
,orch.AMT as 'UnitPrice'
,orch.QTY as 'Qty'
,orch.AMT as 'ChargeAmt'
,orch.DOCTOR as 'Doctor'
,dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
,dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
, doc.CERTIFYPUBLICNO as 'DoctorCertificate'
, doc.CLINIC as 'DoctorClinicCode'
, dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
, dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
, '' as 'DoctorDepartmentCode'
, '' as 'DoctorDepartmentNameTH'
, '' as 'DoctorDepartmentNameEN'
, doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
, dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
, dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
,'' as 'DFDoctor'
,'' as 'DFDoctorNameTH'
,'' as 'DFDoctorNameEN'
,orch.RIGHTCODE as 'RightCode'
,dbo.sysconname(orch.RIGHTCODE,20019,2) as 'RightNameTH'
,dbo.sysconname(orch.RIGHTCODE,20019,1) as 'RightNameEN'
,'' as 'TreatmentDateTime'
,'' as 'NoMinuteDuration'
,'' as 'HNORPostByType'
,'N' as 'Usage'
,orr.CHARGETOVISITDATE as 'ChargeVisitDate'
,orr.CHARGETOVN as 'ChargeVN'
,'' as 'PrescriptionNo'
,orch.IPDCHARGEMAKEDATETIME as 'IPDChargeDateTime'
,orr.CHARGETOAN as 'ChargeAN'
,'' as 'ChargeVoucherNo'
		from ORREQ orr
		inner join ORCHARGE orch on orr.REQUESTNO=orch.REQUESTNO and orr.FACILITYRMSNO=orch.FACILITYRMSNO and orch.TREATMENTCODE is not null
		left join HNDOCTOR doc on orch.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015
Union All
select 
 'PLS' as 'BU'
,orr.HN as 'PatientID'
,orr.FACILITYRMSNO as 'FacilityRmsNo'
,orr.REQUESTNO as 'RequestNo'
,orr.ENTRYDATETIME as 'EntryDateTime'
,oru.CHARGEDATETIME as 'ChargeDateTime'
,oru.SUFFIX as 'SuffixSmall'
,oru.SUFFIX as 'ChargeSuffix'
,oru.STOCKCODE as 'ItemCode'
,dbo.CutSortChar(stm.THAINAME) as 'ItemNameTH'
,dbo.CutSortChar(stm.ENGLISHNAME) as 'ItemNameEN'
,oru.CHARGECODE as 'ActivityCode'
,dbo.sysconname(oru.CHARGECODE,20023,2) as 'ActivityNameTH'
,dbo.sysconname(oru.CHARGECODE,20023,1) as 'ActivityNameEN'
,case when oru.TYPEOFCHARGE = 0 then 'None'
	  when oru.TYPEOFCHARGE = 1 then 'Free'
	  when oru.TYPEOFCHARGE = 2 then 'Refund'
	  when oru.TYPEOFCHARGE = 3 then 'Cxl'
	  when oru.TYPEOFCHARGE = 4 then 'Usage_FOC'
	  when oru.TYPEOFCHARGE = 5 then 'Never_Charge'
	  when oru.TYPEOFCHARGE = 6 then 'Adjust'
	  when oru.TYPEOFCHARGE = 7 then 'Return_Usage_FOC'
 end as 'ChargeType'
,oru.UNITPRICE as 'UnitPrice'
,oru.QTY as 'Qty'
,oru.AMT as 'ChargeAmt'
,oru.DOCTOR as 'Doctor'
,dbo.CutSortChar(doc.THAINAME) as 'DoctorNameTH'
,dbo.CutSortChar(doc.ENGLISHNAME) as 'DoctorNameEN'
, doc.CERTIFYPUBLICNO as 'DoctorCertificate'
, doc.CLINIC as 'DoctorClinicCode'
, dbo.sysconname(doc.CLINIC,20016,2) as 'DoctorClinicNameTH'
, dbo.sysconname(doc.CLINIC,20016,1) as 'DoctorClinicNameEN'
, '' as 'DoctorDepartmentCode'
, '' as 'DoctorDepartmentNameTH'
, '' as 'DoctorDepartmentNameEN'
, doc.SPECIALTY+doc.SUBSPECIALTY as 'DoctorSpecialtyCode'
, dbo.CutSortChar(ssp.THAINAME) as 'DoctorSpecialtyNameTH'
, dbo.CutSortChar(ssp.ENGLISHNAME) as 'DoctorSpecialtyNameEN'
,'' as 'DFDoctor'
,'' as 'DFDoctorNameTH'
,'' as 'DFDoctorNameEN'
,oru.RIGHTCODE as 'RightCode'
,dbo.sysconname(oru.RIGHTCODE,20019,2) as 'RightNameTH'
,dbo.sysconname(oru.RIGHTCODE,20019,1) as 'RightNameEN'
,'' as 'TreatmentDateTime'
,'' as 'NoMinuteDuration'
,'' as 'HNORPostByType'
,'Y' as 'Usage'
,orr.CHARGETOVISITDATE as 'ChargeVisitDate'
,orr.CHARGETOVN as 'ChargeVN'
,'' as 'PrescriptionNo'
,orch.IPDCHARGEMAKEDATETIME as 'IPDChargeDateTime'
,orr.CHARGETOAN as 'ChargeAN'
,oru.CHARGEVOUCHERNO as 'ChargeVoucherNo'
		from ORREQ orr
		inner join ORCHARGE orch on orr.REQUESTNO=orch.REQUESTNO and orr.FACILITYRMSNO=orch.FACILITYRMSNO
		inner join ORUSAGE oru on orch.FACILITYRMSNO=oru.FACILITYRMSNO and orch.REQUESTNO=oru.REQUESTNO and orch.IPDCHARGEMAKEDATETIME=oru.CHARGEDATETIME and orch.TREATMENTCODE is null
		left join SSBSTOCK.dbo.STOCK_MASTER stm on oru.STOCKCODE=stm.STOCKCODE
		left join HNDOCTOR doc on oru.DOCTOR=doc.DOCTOR
		left join SYSCONFIG ssp on doc.SPECIALTY+doc.SUBSPECIALTY = REPLACE(ssp.CODE,' ','') and ssp.CTRLCODE = 20015